// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cout_write_fifo_read (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        cout_burst_buf_V_address0,
        cout_burst_buf_V_ce0,
        cout_burst_buf_V_we0,
        cout_burst_buf_V_d0,
        cout_burst_buf_V_q0,
        cout_burst_buf_V_address1,
        cout_burst_buf_V_ce1,
        cout_burst_buf_V_we1,
        cout_burst_buf_V_d1,
        fifo_cout_V_V_dout,
        fifo_cout_V_V_empty_n,
        fifo_cout_V_V_read,
        en,
        up_sample,
        LAYER_OUT_H,
        LAYER_OUT_W,
        LAYER_OUT_NUM_T,
        LAYER_IN_H_T,
        LAYER_IN_W_T,
        in_h_iter,
        in_w_iter,
        POOL_ODD
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_pp0_stage0 = 9'd2;
parameter    ap_ST_fsm_pp0_stage1 = 9'd4;
parameter    ap_ST_fsm_pp0_stage2 = 9'd8;
parameter    ap_ST_fsm_state21 = 9'd16;
parameter    ap_ST_fsm_pp1_stage0 = 9'd32;
parameter    ap_ST_fsm_pp1_stage1 = 9'd64;
parameter    ap_ST_fsm_pp1_stage2 = 9'd128;
parameter    ap_ST_fsm_pp2_stage0 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] cout_burst_buf_V_address0;
output   cout_burst_buf_V_ce0;
output   cout_burst_buf_V_we0;
output  [511:0] cout_burst_buf_V_d0;
input  [511:0] cout_burst_buf_V_q0;
output  [12:0] cout_burst_buf_V_address1;
output   cout_burst_buf_V_ce1;
output   cout_burst_buf_V_we1;
output  [511:0] cout_burst_buf_V_d1;
input  [255:0] fifo_cout_V_V_dout;
input   fifo_cout_V_V_empty_n;
output   fifo_cout_V_V_read;
input   en;
input   up_sample;
input  [31:0] LAYER_OUT_H;
input  [31:0] LAYER_OUT_W;
input  [15:0] LAYER_OUT_NUM_T;
input  [31:0] LAYER_IN_H_T;
input  [31:0] LAYER_IN_W_T;
input  [31:0] in_h_iter;
input  [31:0] in_w_iter;
input   POOL_ODD;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[12:0] cout_burst_buf_V_address0;
reg cout_burst_buf_V_ce0;
reg cout_burst_buf_V_we0;
reg[511:0] cout_burst_buf_V_d0;
reg cout_burst_buf_V_ce1;
reg cout_burst_buf_V_we1;
reg fifo_cout_V_V_read;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    fifo_cout_V_V_blk_n;
reg    ap_enable_reg_pp2_iter20;
wire    ap_block_pp2_stage0;
reg   [0:0] done_reg_336;
reg   [0:0] done_reg_336_pp2_iter19_reg;
wire    ap_CS_fsm_pp1_stage2;
reg    ap_enable_reg_pp1_iter5;
wire    ap_block_pp1_stage2;
reg   [0:0] done4_reg_288;
reg   [0:0] done4_reg_288_pp1_iter5_reg;
wire    ap_CS_fsm_pp0_stage2;
reg    ap_enable_reg_pp0_iter5;
wire    ap_block_pp0_stage2;
reg   [0:0] done1_reg_240;
reg   [0:0] done1_reg_240_pp0_iter5_reg;
reg   [31:0] o7_reg_204;
reg   [31:0] o7_reg_204_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state3_pp0_stage1_iter0;
wire    ap_block_state6_pp0_stage1_iter1;
wire    ap_block_state9_pp0_stage1_iter2;
wire    ap_block_state12_pp0_stage1_iter3;
wire    ap_block_state15_pp0_stage1_iter4;
wire    ap_block_state18_pp0_stage1_iter5;
wire    ap_block_pp0_stage1_11001;
reg   [31:0] o7_reg_204_pp0_iter2_reg;
reg   [31:0] o7_reg_204_pp0_iter3_reg;
reg   [31:0] o7_reg_204_pp0_iter4_reg;
reg  signed [31:0] h7_reg_216;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_state8_pp0_stage0_iter2;
wire    ap_block_state11_pp0_stage0_iter3;
wire    ap_block_state14_pp0_stage0_iter4;
wire    ap_block_state17_pp0_stage0_iter5;
wire    ap_block_state20_pp0_stage0_iter6;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] w7_reg_228;
reg   [31:0] w7_reg_228_pp0_iter1_reg;
reg   [31:0] w7_reg_228_pp0_iter2_reg;
reg   [0:0] done1_reg_240_pp0_iter1_reg;
reg   [0:0] done1_reg_240_pp0_iter2_reg;
reg   [0:0] done1_reg_240_pp0_iter3_reg;
reg   [0:0] done1_reg_240_pp0_iter4_reg;
reg   [31:0] o1_reg_252;
reg   [31:0] o1_reg_252_pp1_iter1_reg;
wire    ap_CS_fsm_pp1_stage1;
wire    ap_block_state23_pp1_stage1_iter0;
wire    ap_block_state26_pp1_stage1_iter1;
wire    ap_block_state29_pp1_stage1_iter2;
wire    ap_block_state32_pp1_stage1_iter3;
wire    ap_block_state35_pp1_stage1_iter4;
wire    ap_block_state38_pp1_stage1_iter5;
wire    ap_block_pp1_stage1_11001;
reg   [31:0] o1_reg_252_pp1_iter2_reg;
reg   [31:0] o1_reg_252_pp1_iter3_reg;
reg   [31:0] o1_reg_252_pp1_iter4_reg;
reg  signed [31:0] h2_reg_264;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state22_pp1_stage0_iter0;
wire    ap_block_state25_pp1_stage0_iter1;
wire    ap_block_state28_pp1_stage0_iter2;
wire    ap_block_state31_pp1_stage0_iter3;
wire    ap_block_state34_pp1_stage0_iter4;
wire    ap_block_state37_pp1_stage0_iter5;
wire    ap_block_state40_pp1_stage0_iter6;
wire    ap_block_pp1_stage0_11001;
reg   [31:0] w3_reg_276;
reg   [31:0] w3_reg_276_pp1_iter1_reg;
reg   [31:0] w3_reg_276_pp1_iter2_reg;
reg   [0:0] done4_reg_288_pp1_iter1_reg;
reg   [0:0] done4_reg_288_pp1_iter2_reg;
reg   [0:0] done4_reg_288_pp1_iter3_reg;
reg   [0:0] done4_reg_288_pp1_iter4_reg;
reg   [31:0] o_reg_300;
reg   [31:0] o_reg_300_pp2_iter2_reg;
wire    ap_block_state41_pp2_stage0_iter0;
wire    ap_block_state42_pp2_stage0_iter1;
wire    ap_block_state43_pp2_stage0_iter2;
wire    ap_block_state44_pp2_stage0_iter3;
wire    ap_block_state45_pp2_stage0_iter4;
wire    ap_block_state46_pp2_stage0_iter5;
wire    ap_block_state47_pp2_stage0_iter6;
wire    ap_block_state48_pp2_stage0_iter7;
wire    ap_block_state49_pp2_stage0_iter8;
wire    ap_block_state50_pp2_stage0_iter9;
wire    ap_block_state51_pp2_stage0_iter10;
wire    ap_block_state52_pp2_stage0_iter11;
wire    ap_block_state53_pp2_stage0_iter12;
wire    ap_block_state54_pp2_stage0_iter13;
wire    ap_block_state55_pp2_stage0_iter14;
wire    ap_block_state56_pp2_stage0_iter15;
wire    ap_block_state57_pp2_stage0_iter16;
wire    ap_block_state58_pp2_stage0_iter17;
wire    ap_block_state59_pp2_stage0_iter18;
wire    ap_block_state60_pp2_stage0_iter19;
reg    ap_block_state61_pp2_stage0_iter20;
wire    ap_block_state62_pp2_stage0_iter21;
reg    ap_block_pp2_stage0_11001;
reg   [31:0] o_reg_300_pp2_iter3_reg;
reg   [31:0] o_reg_300_pp2_iter4_reg;
reg   [31:0] o_reg_300_pp2_iter5_reg;
reg   [31:0] o_reg_300_pp2_iter6_reg;
reg   [31:0] o_reg_300_pp2_iter7_reg;
reg   [31:0] o_reg_300_pp2_iter8_reg;
reg   [31:0] o_reg_300_pp2_iter9_reg;
reg   [31:0] o_reg_300_pp2_iter10_reg;
reg   [31:0] o_reg_300_pp2_iter11_reg;
reg   [31:0] o_reg_300_pp2_iter12_reg;
reg   [31:0] o_reg_300_pp2_iter13_reg;
reg   [31:0] o_reg_300_pp2_iter14_reg;
reg   [31:0] o_reg_300_pp2_iter15_reg;
reg  signed [31:0] h_reg_312;
wire    ap_CS_fsm_pp2_stage0;
reg   [31:0] w_reg_324;
reg   [31:0] w_reg_324_pp2_iter1_reg;
reg   [31:0] w_reg_324_pp2_iter2_reg;
reg   [31:0] w_reg_324_pp2_iter3_reg;
reg   [31:0] w_reg_324_pp2_iter4_reg;
reg   [31:0] w_reg_324_pp2_iter5_reg;
reg   [31:0] w_reg_324_pp2_iter6_reg;
reg   [31:0] w_reg_324_pp2_iter7_reg;
reg   [0:0] done_reg_336_pp2_iter1_reg;
reg   [0:0] done_reg_336_pp2_iter2_reg;
reg   [0:0] done_reg_336_pp2_iter3_reg;
reg   [0:0] done_reg_336_pp2_iter4_reg;
reg   [0:0] done_reg_336_pp2_iter5_reg;
reg   [0:0] done_reg_336_pp2_iter6_reg;
reg   [0:0] done_reg_336_pp2_iter7_reg;
reg   [0:0] done_reg_336_pp2_iter8_reg;
reg   [0:0] done_reg_336_pp2_iter9_reg;
reg   [0:0] done_reg_336_pp2_iter10_reg;
reg   [0:0] done_reg_336_pp2_iter11_reg;
reg   [0:0] done_reg_336_pp2_iter12_reg;
reg   [0:0] done_reg_336_pp2_iter13_reg;
reg   [0:0] done_reg_336_pp2_iter14_reg;
reg   [0:0] done_reg_336_pp2_iter15_reg;
reg   [0:0] done_reg_336_pp2_iter16_reg;
reg   [0:0] done_reg_336_pp2_iter17_reg;
reg   [0:0] done_reg_336_pp2_iter18_reg;
reg   [0:0] done_reg_336_pp2_iter20_reg;
reg   [255:0] reg_368;
wire    ap_block_state4_pp0_stage2_iter0;
wire    ap_block_state7_pp0_stage2_iter1;
wire    ap_block_state10_pp0_stage2_iter2;
wire    ap_block_state13_pp0_stage2_iter3;
wire    ap_block_state16_pp0_stage2_iter4;
reg    ap_block_state19_pp0_stage2_iter5;
reg    ap_block_pp0_stage2_11001;
wire    ap_block_state24_pp1_stage2_iter0;
wire    ap_block_state27_pp1_stage2_iter1;
wire    ap_block_state30_pp1_stage2_iter2;
wire    ap_block_state33_pp1_stage2_iter3;
wire    ap_block_state36_pp1_stage2_iter4;
reg    ap_block_state39_pp1_stage2_iter5;
reg    ap_block_pp1_stage2_11001;
wire   [31:0] LAYER_OUT_NUM_T_cast_fu_372_p1;
reg   [31:0] LAYER_OUT_NUM_T_cast_reg_1131;
wire   [1:0] write_2_fu_422_p3;
wire   [31:0] tmp_532_fu_430_p2;
reg   [31:0] tmp_532_reg_1142;
wire   [31:0] tmp_533_fu_436_p2;
reg   [31:0] tmp_533_reg_1147;
wire   [31:0] tmp_534_fu_442_p2;
reg   [31:0] tmp_534_reg_1152;
wire   [31:0] tmp_535_fu_448_p2;
reg   [31:0] tmp_535_reg_1157;
wire   [31:0] tmp_218_cast_fu_454_p1;
reg   [31:0] tmp_218_cast_reg_1162;
wire   [31:0] tmp_331_fu_468_p1;
reg   [31:0] tmp_331_reg_1167;
wire   [31:0] tmp_332_fu_482_p1;
reg   [31:0] tmp_332_reg_1173;
wire   [31:0] tmp_333_fu_496_p1;
reg   [31:0] tmp_333_reg_1178;
wire   [31:0] tmp_334_fu_510_p1;
reg   [31:0] tmp_334_reg_1183;
wire   [31:0] tmp_213_cast_fu_514_p1;
reg   [31:0] tmp_213_cast_reg_1188;
wire   [31:0] tmp_cast_fu_518_p1;
reg   [31:0] tmp_cast_reg_1193;
wire   [31:0] tmp_229_fu_527_p2;
reg   [31:0] tmp_229_reg_1198;
reg   [0:0] ap_phi_mux_done1_phi_fu_244_p4;
wire   [31:0] tmp_237_fu_532_p2;
reg   [31:0] tmp_237_reg_1203;
wire   [31:0] w_8_fu_537_p2;
reg   [31:0] w_8_reg_1208;
wire   [31:0] h_8_fu_543_p2;
reg   [31:0] h_8_reg_1214;
wire   [0:0] sel_tmp28_fu_557_p2;
reg   [0:0] sel_tmp28_reg_1220;
reg   [0:0] sel_tmp28_reg_1220_pp0_iter1_reg;
reg   [0:0] sel_tmp28_reg_1220_pp0_iter2_reg;
reg   [0:0] sel_tmp28_reg_1220_pp0_iter3_reg;
reg   [0:0] sel_tmp28_reg_1220_pp0_iter4_reg;
reg   [0:0] sel_tmp28_reg_1220_pp0_iter5_reg;
wire   [0:0] tmp_245_fu_563_p2;
reg   [0:0] tmp_245_reg_1226;
wire   [31:0] o_9_fu_571_p2;
reg   [31:0] o_9_reg_1232;
wire   [0:0] sel_tmp29_fu_577_p2;
reg   [0:0] sel_tmp29_reg_1238;
wire   [31:0] h11_2_fu_590_p3;
reg   [31:0] h11_2_reg_1244;
reg    ap_enable_reg_pp0_iter0;
wire   [31:0] o10_3_fu_616_p3;
reg   [31:0] o10_3_reg_1249;
wire   [31:0] w12_1_fu_623_p3;
reg   [31:0] w12_1_reg_1254;
wire   [0:0] done13_3_fu_629_p2;
reg   [0:0] done13_3_reg_1259;
wire   [31:0] grp_fu_522_p2;
reg   [31:0] tmp_220_reg_1264;
wire  signed [31:0] tmp_224_fu_639_p2;
reg  signed [31:0] tmp_224_reg_1269;
wire   [31:0] grp_fu_645_p2;
reg   [31:0] tmp_225_reg_1274;
reg   [12:0] cout_burst_buf_V_add_2_reg_1279;
reg   [0:0] tmp_545_reg_1284;
wire   [31:0] tmp_218_fu_743_p2;
reg   [31:0] tmp_218_reg_1292;
reg   [0:0] ap_phi_mux_done4_phi_fu_292_p4;
wire   [31:0] tmp_234_fu_748_p2;
reg   [31:0] tmp_234_reg_1297;
wire   [31:0] w_7_fu_753_p2;
reg   [31:0] w_7_reg_1302;
wire   [31:0] h_7_fu_759_p2;
reg   [31:0] h_7_reg_1308;
wire   [0:0] sel_tmp20_fu_773_p2;
reg   [0:0] sel_tmp20_reg_1314;
reg   [0:0] sel_tmp20_reg_1314_pp1_iter1_reg;
reg   [0:0] sel_tmp20_reg_1314_pp1_iter2_reg;
reg   [0:0] sel_tmp20_reg_1314_pp1_iter3_reg;
reg   [0:0] sel_tmp20_reg_1314_pp1_iter4_reg;
reg   [0:0] sel_tmp20_reg_1314_pp1_iter5_reg;
wire   [0:0] tmp_243_fu_779_p2;
reg   [0:0] tmp_243_reg_1320;
wire   [31:0] o_8_fu_787_p2;
reg   [31:0] o_8_reg_1326;
wire   [0:0] sel_tmp24_fu_793_p2;
reg   [0:0] sel_tmp24_reg_1332;
wire   [31:0] h2_2_fu_806_p3;
reg   [31:0] h2_2_reg_1338;
reg    ap_enable_reg_pp1_iter0;
wire   [31:0] o1_3_fu_832_p3;
reg   [31:0] o1_3_reg_1343;
wire   [31:0] w3_1_fu_839_p3;
reg   [31:0] w3_1_reg_1348;
wire   [0:0] done4_3_fu_845_p2;
reg   [0:0] done4_3_reg_1353;
wire   [31:0] grp_fu_738_p2;
reg   [31:0] tmp_212_reg_1358;
wire  signed [31:0] tmp_213_fu_850_p2;
reg  signed [31:0] tmp_213_reg_1363;
wire   [31:0] grp_fu_855_p2;
reg   [31:0] tmp_214_reg_1368;
reg   [12:0] cout_burst_buf_V_add_1_reg_1373;
reg   [0:0] tmp_541_reg_1378;
wire   [0:0] tmp_241_fu_954_p2;
reg   [0:0] tmp_241_reg_1386;
reg   [0:0] ap_phi_mux_done_phi_fu_340_p4;
wire   [31:0] h_6_fu_959_p2;
reg   [31:0] h_6_reg_1393;
wire   [31:0] w_1_fu_965_p3;
reg   [31:0] w_1_reg_1399;
reg    ap_enable_reg_pp2_iter0;
wire   [31:0] o_3_fu_1014_p3;
reg   [31:0] o_3_reg_1404;
reg    ap_enable_reg_pp2_iter1;
wire   [31:0] h_2_fu_1028_p3;
wire   [0:0] done_3_fu_1035_p2;
wire   [31:0] grp_fu_973_p2;
reg   [31:0] tmp_204_reg_1419;
wire  signed [31:0] tmp_205_fu_1041_p2;
reg  signed [31:0] tmp_205_reg_1424;
wire   [31:0] grp_fu_1046_p2;
reg   [31:0] tmp_206_reg_1429;
reg   [12:0] cout_burst_buf_V_add_reg_1434;
reg   [12:0] cout_burst_buf_V_add_reg_1434_pp2_iter17_reg;
reg   [12:0] cout_burst_buf_V_add_reg_1434_pp2_iter18_reg;
reg   [12:0] cout_burst_buf_V_add_reg_1434_pp2_iter19_reg;
reg   [12:0] cout_burst_buf_V_add_reg_1434_pp2_iter20_reg;
reg   [0:0] tmp_538_reg_1440;
reg   [0:0] tmp_538_reg_1440_pp2_iter17_reg;
reg   [0:0] tmp_538_reg_1440_pp2_iter18_reg;
reg   [0:0] tmp_538_reg_1440_pp2_iter19_reg;
wire   [255:0] cout_buf_0_V_fu_1084_p1;
reg   [255:0] cout_buf_0_V_reg_1446;
wire   [255:0] grp_fu_358_p4;
reg   [255:0] cout_buf_1_V_reg_1451;
reg    ap_enable_reg_pp2_iter19;
wire   [255:0] cout_buf_1_V_13_fu_1088_p3;
reg   [255:0] cout_buf_1_V_13_reg_1456;
wire   [255:0] cout_buf_0_V_13_fu_1094_p3;
reg   [255:0] cout_buf_0_V_13_reg_1461;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage2_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter6;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state22;
reg    ap_enable_reg_pp1_iter1;
reg    ap_block_pp1_stage2_subdone;
reg    ap_enable_reg_pp1_iter2;
reg    ap_enable_reg_pp1_iter3;
reg    ap_enable_reg_pp1_iter4;
reg    ap_enable_reg_pp1_iter6;
reg    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state41;
reg    ap_enable_reg_pp2_iter2;
reg    ap_enable_reg_pp2_iter3;
reg    ap_enable_reg_pp2_iter4;
reg    ap_enable_reg_pp2_iter5;
reg    ap_enable_reg_pp2_iter6;
reg    ap_enable_reg_pp2_iter7;
reg    ap_enable_reg_pp2_iter8;
reg    ap_enable_reg_pp2_iter9;
reg    ap_enable_reg_pp2_iter10;
reg    ap_enable_reg_pp2_iter11;
reg    ap_enable_reg_pp2_iter12;
reg    ap_enable_reg_pp2_iter13;
reg    ap_enable_reg_pp2_iter14;
reg    ap_enable_reg_pp2_iter15;
reg    ap_enable_reg_pp2_iter16;
reg    ap_enable_reg_pp2_iter17;
reg    ap_enable_reg_pp2_iter18;
reg    ap_enable_reg_pp2_iter21;
reg   [31:0] ap_phi_mux_o7_phi_fu_208_p4;
wire    ap_block_pp0_stage1;
reg  signed [31:0] ap_phi_mux_h7_phi_fu_220_p4;
wire    ap_block_pp0_stage0;
reg   [31:0] ap_phi_mux_w7_phi_fu_232_p4;
reg   [31:0] ap_phi_mux_o1_phi_fu_256_p4;
wire    ap_block_pp1_stage1;
reg  signed [31:0] ap_phi_mux_h2_phi_fu_268_p4;
wire    ap_block_pp1_stage0;
reg   [31:0] ap_phi_mux_w3_phi_fu_280_p4;
reg   [31:0] ap_phi_mux_o_phi_fu_304_p4;
reg  signed [31:0] ap_phi_mux_h_phi_fu_316_p4;
reg   [31:0] ap_phi_mux_w_phi_fu_328_p4;
wire   [63:0] tmp_228_fu_670_p1;
wire   [63:0] tmp_217_fu_880_p1;
wire   [63:0] tmp_209_fu_1071_p1;
wire   [511:0] p_Result_2_fu_729_p3;
wire   [511:0] p_Result_1_fu_939_p3;
wire   [0:0] brmerge_fu_376_p0;
wire   [0:0] brmerge_fu_376_p1;
wire   [0:0] brmerge_fu_376_p2;
wire   [0:0] brmerge1_fu_388_p0;
wire   [0:0] brmerge_not_fu_382_p2;
wire   [0:0] p_s_fu_394_p0;
wire   [0:0] POOL_ODD_not_fu_402_p0;
wire   [0:0] sel_tmp_fu_408_p0;
wire   [0:0] POOL_ODD_not_fu_402_p2;
wire   [0:0] sel_tmp_fu_408_p2;
wire   [1:0] p_s_fu_394_p3;
wire   [0:0] brmerge1_fu_388_p2;
wire   [1:0] sel_tmp26_fu_414_p3;
wire  signed [31:0] tmp_532_fu_430_p0;
wire   [12:0] grp_fu_348_p4;
wire  signed [31:0] tmp_s_fu_458_p1;
wire   [30:0] tmp_s_fu_458_p4;
wire   [30:0] tmp_195_fu_472_p4;
wire   [30:0] tmp_196_fu_486_p4;
wire   [30:0] tmp_197_fu_500_p4;
wire   [0:0] tmp_230_fu_549_p2;
wire   [0:0] tmp_238_fu_553_p2;
wire   [0:0] tmp_248_fu_567_p2;
wire   [31:0] sel_tmp31_fu_583_p3;
wire   [0:0] tmp_251_fu_598_p2;
wire   [31:0] p_3_fu_602_p3;
wire   [31:0] sel_tmp30_fu_609_p3;
wire   [31:0] tmp_542_fu_634_p2;
wire   [15:0] grp_fu_645_p1;
wire   [31:0] tmp_543_fu_649_p2;
wire   [31:0] local_cout_idx_2_fu_655_p2;
wire   [27:0] tmp_227_fu_660_p4;
wire   [255:0] cout_buf_0_V_9_fu_683_p1;
wire   [255:0] cout_buf_1_V_11_fu_701_p3;
wire   [255:0] cout_buf_1_V_6_fu_687_p3;
wire   [255:0] cout_buf_0_V_11_fu_708_p3;
wire   [255:0] cout_buf_0_V_6_fu_694_p3;
wire   [255:0] cout_buf_1_V_15_fu_715_p3;
wire   [255:0] cout_buf_0_V_15_fu_722_p3;
wire   [30:0] grp_fu_738_p0;
wire   [0:0] tmp_219_fu_765_p2;
wire   [0:0] tmp_235_fu_769_p2;
wire   [0:0] tmp_247_fu_783_p2;
wire   [31:0] sel_tmp27_fu_799_p3;
wire   [0:0] tmp_250_fu_814_p2;
wire   [31:0] p_2_fu_818_p3;
wire   [31:0] sel_tmp25_fu_825_p3;
wire   [15:0] grp_fu_855_p1;
wire   [31:0] tmp_539_fu_859_p2;
wire   [31:0] local_cout_idx_1_fu_865_p2;
wire   [27:0] tmp_216_fu_870_p4;
wire   [255:0] cout_buf_0_V_3_fu_893_p1;
wire   [255:0] cout_buf_1_V_8_fu_911_p3;
wire   [255:0] cout_buf_1_V_5_fu_897_p3;
wire   [255:0] cout_buf_0_V_7_fu_918_p3;
wire   [255:0] cout_buf_0_V_4_fu_904_p3;
wire   [255:0] cout_buf_1_V_14_fu_925_p3;
wire   [255:0] cout_buf_0_V_14_fu_932_p3;
wire   [31:0] w_6_fu_948_p2;
wire  signed [31:0] tmp_241_fu_954_p1;
wire   [31:0] o_7_fu_982_p2;
wire   [0:0] tmp_249_fu_988_p2;
wire   [0:0] tmp_246_fu_978_p2;
wire   [0:0] sel_tmp4_fu_1001_p2;
wire   [31:0] p_1_fu_993_p3;
wire   [31:0] sel_tmp5_fu_1006_p3;
wire   [31:0] sel_tmp9_fu_1021_p3;
wire   [15:0] grp_fu_1046_p1;
wire   [31:0] tmp_536_fu_1050_p2;
wire   [31:0] local_cout_idx_fu_1056_p2;
wire   [27:0] tmp_208_fu_1061_p4;
reg    grp_fu_522_ce;
reg    grp_fu_645_ce;
reg    grp_fu_738_ce;
reg    grp_fu_855_ce;
reg    grp_fu_973_ce;
reg    grp_fu_1046_ce;
wire    ap_CS_fsm_state21;
reg   [8:0] ap_NS_fsm;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp1_stage1_subdone;
reg    ap_block_pp0;
reg    ap_block_pp1;
reg    ap_block_pp2;
reg    ap_enable_operation_277;
reg    ap_enable_state58_pp2_iter17_stage0;
reg    ap_enable_operation_279;
reg    ap_enable_state60_pp2_iter19_stage0;
reg    ap_enable_operation_288;
reg    ap_enable_state62_pp2_iter21_stage0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 ap_enable_reg_pp2_iter20 = 1'b0;
#0 ap_enable_reg_pp1_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter4 = 1'b0;
#0 ap_enable_reg_pp1_iter6 = 1'b0;
#0 ap_enable_reg_pp2_iter2 = 1'b0;
#0 ap_enable_reg_pp2_iter3 = 1'b0;
#0 ap_enable_reg_pp2_iter4 = 1'b0;
#0 ap_enable_reg_pp2_iter5 = 1'b0;
#0 ap_enable_reg_pp2_iter6 = 1'b0;
#0 ap_enable_reg_pp2_iter7 = 1'b0;
#0 ap_enable_reg_pp2_iter8 = 1'b0;
#0 ap_enable_reg_pp2_iter9 = 1'b0;
#0 ap_enable_reg_pp2_iter10 = 1'b0;
#0 ap_enable_reg_pp2_iter11 = 1'b0;
#0 ap_enable_reg_pp2_iter12 = 1'b0;
#0 ap_enable_reg_pp2_iter13 = 1'b0;
#0 ap_enable_reg_pp2_iter14 = 1'b0;
#0 ap_enable_reg_pp2_iter15 = 1'b0;
#0 ap_enable_reg_pp2_iter16 = 1'b0;
#0 ap_enable_reg_pp2_iter17 = 1'b0;
#0 ap_enable_reg_pp2_iter18 = 1'b0;
#0 ap_enable_reg_pp2_iter21 = 1'b0;
end

top_kernel_mul_32bkb #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
top_kernel_mul_32bkb_U305(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(LAYER_IN_W_T),
    .din1(ap_phi_mux_h7_phi_fu_220_p4),
    .ce(grp_fu_522_ce),
    .dout(grp_fu_522_p2)
);

top_kernel_mul_32g8j #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
top_kernel_mul_32g8j_U306(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_224_reg_1269),
    .din1(grp_fu_645_p1),
    .ce(grp_fu_645_ce),
    .dout(grp_fu_645_p2)
);

top_kernel_mul_31Thq #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
top_kernel_mul_31Thq_U307(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_738_p0),
    .din1(ap_phi_mux_h2_phi_fu_268_p4),
    .ce(grp_fu_738_ce),
    .dout(grp_fu_738_p2)
);

top_kernel_mul_32g8j #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
top_kernel_mul_32g8j_U308(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_213_reg_1363),
    .din1(grp_fu_855_p1),
    .ce(grp_fu_855_ce),
    .dout(grp_fu_855_p2)
);

top_kernel_mul_32bkb #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
top_kernel_mul_32bkb_U309(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(LAYER_IN_W_T),
    .din1(h_reg_312),
    .ce(grp_fu_973_ce),
    .dout(grp_fu_973_p2)
);

top_kernel_mul_32g8j #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
top_kernel_mul_32g8j_U310(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_205_reg_1424),
    .din1(grp_fu_1046_p1),
    .ce(grp_fu_1046_ce),
    .dout(grp_fu_1046_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((write_2_fu_422_p3 == 2'd2) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end else if (((write_2_fu_422_p3 == 2'd2) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter6 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state22) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((write_2_fu_422_p3 == 2'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage2_subdone) & (1'b1 == ap_CS_fsm_pp1_stage2))) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage2_subdone) & (1'b1 == ap_CS_fsm_pp1_stage2))) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage2_subdone) & (1'b1 == ap_CS_fsm_pp1_stage2))) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage2_subdone) & (1'b1 == ap_CS_fsm_pp1_stage2))) begin
            ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage2_subdone) & (1'b1 == ap_CS_fsm_pp1_stage2))) begin
            ap_enable_reg_pp1_iter5 <= ap_enable_reg_pp1_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter6 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp1_stage2_subdone) & (1'b1 == ap_CS_fsm_pp1_stage2)) | ((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
            ap_enable_reg_pp1_iter6 <= ap_enable_reg_pp1_iter5;
        end else if (((write_2_fu_422_p3 == 2'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp1_iter6 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state41) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if (((write_2_fu_422_p3 == 2'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp2_exit_iter0_state41)) begin
                ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state41);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter10 <= ap_enable_reg_pp2_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter11 <= ap_enable_reg_pp2_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter12 <= ap_enable_reg_pp2_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter13 <= ap_enable_reg_pp2_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter14 <= ap_enable_reg_pp2_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter15 <= ap_enable_reg_pp2_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter16 <= ap_enable_reg_pp2_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter17 <= ap_enable_reg_pp2_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter18 <= ap_enable_reg_pp2_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter19 <= ap_enable_reg_pp2_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter2 <= ap_enable_reg_pp2_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter20 <= ap_enable_reg_pp2_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter21 <= ap_enable_reg_pp2_iter20;
        end else if (((write_2_fu_422_p3 == 2'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp2_iter21 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter3 <= ap_enable_reg_pp2_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter4 <= ap_enable_reg_pp2_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter5 <= ap_enable_reg_pp2_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter6 <= ap_enable_reg_pp2_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter7 <= ap_enable_reg_pp2_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter8 <= ap_enable_reg_pp2_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter9 <= ap_enable_reg_pp2_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((write_2_fu_422_p3 == 2'd2) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        done1_reg_240 <= 1'd0;
    end else if (((done1_reg_240 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        done1_reg_240 <= done13_3_reg_1259;
    end
end

always @ (posedge ap_clk) begin
    if (((write_2_fu_422_p3 == 2'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        done4_reg_288 <= 1'd0;
    end else if (((done4_reg_288 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        done4_reg_288 <= done4_3_reg_1353;
    end
end

always @ (posedge ap_clk) begin
    if (((write_2_fu_422_p3 == 2'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        done_reg_336 <= 1'd0;
    end else if (((done_reg_336 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        done_reg_336 <= done_3_fu_1035_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((write_2_fu_422_p3 == 2'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        h2_reg_264 <= 32'd0;
    end else if (((done4_reg_288 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        h2_reg_264 <= h2_2_reg_1338;
    end
end

always @ (posedge ap_clk) begin
    if (((write_2_fu_422_p3 == 2'd2) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        h7_reg_216 <= 32'd0;
    end else if (((done1_reg_240 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        h7_reg_216 <= h11_2_reg_1244;
    end
end

always @ (posedge ap_clk) begin
    if (((write_2_fu_422_p3 == 2'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        h_reg_312 <= 32'd0;
    end else if (((done_reg_336 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        h_reg_312 <= h_2_fu_1028_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((write_2_fu_422_p3 == 2'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        o1_reg_252 <= 32'd0;
    end else if (((done4_reg_288_pp1_iter1_reg == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001))) begin
        o1_reg_252 <= o1_3_reg_1343;
    end
end

always @ (posedge ap_clk) begin
    if (((write_2_fu_422_p3 == 2'd2) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        o7_reg_204 <= 32'd0;
    end else if (((done1_reg_240_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        o7_reg_204 <= o10_3_reg_1249;
    end
end

always @ (posedge ap_clk) begin
    if (((write_2_fu_422_p3 == 2'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        o_reg_300 <= 32'd0;
    end else if (((done_reg_336_pp2_iter1_reg == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter2 == 1'b1))) begin
        o_reg_300 <= o_3_reg_1404;
    end
end

always @ (posedge ap_clk) begin
    if (((write_2_fu_422_p3 == 2'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        w3_reg_276 <= 32'd0;
    end else if (((done4_reg_288 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        w3_reg_276 <= w3_1_reg_1348;
    end
end

always @ (posedge ap_clk) begin
    if (((write_2_fu_422_p3 == 2'd2) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        w7_reg_228 <= 32'd0;
    end else if (((done1_reg_240 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w7_reg_228 <= w12_1_reg_1254;
    end
end

always @ (posedge ap_clk) begin
    if (((write_2_fu_422_p3 == 2'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        w_reg_324 <= 32'd0;
    end else if (((done_reg_336 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        w_reg_324 <= w_1_reg_1399;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        LAYER_OUT_NUM_T_cast_reg_1131[15 : 0] <= LAYER_OUT_NUM_T_cast_fu_372_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((done_reg_336_pp2_iter19_reg == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        cout_buf_0_V_13_reg_1461 <= cout_buf_0_V_13_fu_1094_p3;
        cout_buf_1_V_13_reg_1456 <= cout_buf_1_V_13_fu_1088_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((done_reg_336_pp2_iter18_reg == 1'd0) & (tmp_538_reg_1440_pp2_iter18_reg == 1'd1) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        cout_buf_0_V_reg_1446 <= cout_buf_0_V_fu_1084_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_538_reg_1440_pp2_iter18_reg == 1'd0) & (done_reg_336_pp2_iter18_reg == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter19 == 1'b1))) begin
        cout_buf_1_V_reg_1451 <= {{cout_burst_buf_V_q0[511:256]}};
    end
end

always @ (posedge ap_clk) begin
    if (((done4_reg_288_pp1_iter4_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        cout_burst_buf_V_add_1_reg_1373 <= tmp_217_fu_880_p1;
        tmp_541_reg_1378 <= local_cout_idx_1_fu_865_p2[32'd3];
    end
end

always @ (posedge ap_clk) begin
    if (((done1_reg_240_pp0_iter4_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cout_burst_buf_V_add_2_reg_1279 <= tmp_228_fu_670_p1;
        tmp_545_reg_1284 <= local_cout_idx_2_fu_655_p2[32'd3];
    end
end

always @ (posedge ap_clk) begin
    if (((done_reg_336_pp2_iter15_reg == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        cout_burst_buf_V_add_reg_1434 <= tmp_209_fu_1071_p1;
        tmp_538_reg_1440 <= local_cout_idx_fu_1056_p2[32'd3];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp2_stage0_11001)) begin
        cout_burst_buf_V_add_reg_1434_pp2_iter17_reg <= cout_burst_buf_V_add_reg_1434;
        cout_burst_buf_V_add_reg_1434_pp2_iter18_reg <= cout_burst_buf_V_add_reg_1434_pp2_iter17_reg;
        cout_burst_buf_V_add_reg_1434_pp2_iter19_reg <= cout_burst_buf_V_add_reg_1434_pp2_iter18_reg;
        cout_burst_buf_V_add_reg_1434_pp2_iter20_reg <= cout_burst_buf_V_add_reg_1434_pp2_iter19_reg;
        done_reg_336_pp2_iter10_reg <= done_reg_336_pp2_iter9_reg;
        done_reg_336_pp2_iter11_reg <= done_reg_336_pp2_iter10_reg;
        done_reg_336_pp2_iter12_reg <= done_reg_336_pp2_iter11_reg;
        done_reg_336_pp2_iter13_reg <= done_reg_336_pp2_iter12_reg;
        done_reg_336_pp2_iter14_reg <= done_reg_336_pp2_iter13_reg;
        done_reg_336_pp2_iter15_reg <= done_reg_336_pp2_iter14_reg;
        done_reg_336_pp2_iter16_reg <= done_reg_336_pp2_iter15_reg;
        done_reg_336_pp2_iter17_reg <= done_reg_336_pp2_iter16_reg;
        done_reg_336_pp2_iter18_reg <= done_reg_336_pp2_iter17_reg;
        done_reg_336_pp2_iter19_reg <= done_reg_336_pp2_iter18_reg;
        done_reg_336_pp2_iter20_reg <= done_reg_336_pp2_iter19_reg;
        done_reg_336_pp2_iter2_reg <= done_reg_336_pp2_iter1_reg;
        done_reg_336_pp2_iter3_reg <= done_reg_336_pp2_iter2_reg;
        done_reg_336_pp2_iter4_reg <= done_reg_336_pp2_iter3_reg;
        done_reg_336_pp2_iter5_reg <= done_reg_336_pp2_iter4_reg;
        done_reg_336_pp2_iter6_reg <= done_reg_336_pp2_iter5_reg;
        done_reg_336_pp2_iter7_reg <= done_reg_336_pp2_iter6_reg;
        done_reg_336_pp2_iter8_reg <= done_reg_336_pp2_iter7_reg;
        done_reg_336_pp2_iter9_reg <= done_reg_336_pp2_iter8_reg;
        o_reg_300_pp2_iter10_reg <= o_reg_300_pp2_iter9_reg;
        o_reg_300_pp2_iter11_reg <= o_reg_300_pp2_iter10_reg;
        o_reg_300_pp2_iter12_reg <= o_reg_300_pp2_iter11_reg;
        o_reg_300_pp2_iter13_reg <= o_reg_300_pp2_iter12_reg;
        o_reg_300_pp2_iter14_reg <= o_reg_300_pp2_iter13_reg;
        o_reg_300_pp2_iter15_reg <= o_reg_300_pp2_iter14_reg;
        o_reg_300_pp2_iter2_reg <= o_reg_300;
        o_reg_300_pp2_iter3_reg <= o_reg_300_pp2_iter2_reg;
        o_reg_300_pp2_iter4_reg <= o_reg_300_pp2_iter3_reg;
        o_reg_300_pp2_iter5_reg <= o_reg_300_pp2_iter4_reg;
        o_reg_300_pp2_iter6_reg <= o_reg_300_pp2_iter5_reg;
        o_reg_300_pp2_iter7_reg <= o_reg_300_pp2_iter6_reg;
        o_reg_300_pp2_iter8_reg <= o_reg_300_pp2_iter7_reg;
        o_reg_300_pp2_iter9_reg <= o_reg_300_pp2_iter8_reg;
        tmp_538_reg_1440_pp2_iter17_reg <= tmp_538_reg_1440;
        tmp_538_reg_1440_pp2_iter18_reg <= tmp_538_reg_1440_pp2_iter17_reg;
        tmp_538_reg_1440_pp2_iter19_reg <= tmp_538_reg_1440_pp2_iter18_reg;
        w_reg_324_pp2_iter2_reg <= w_reg_324_pp2_iter1_reg;
        w_reg_324_pp2_iter3_reg <= w_reg_324_pp2_iter2_reg;
        w_reg_324_pp2_iter4_reg <= w_reg_324_pp2_iter3_reg;
        w_reg_324_pp2_iter5_reg <= w_reg_324_pp2_iter4_reg;
        w_reg_324_pp2_iter6_reg <= w_reg_324_pp2_iter5_reg;
        w_reg_324_pp2_iter7_reg <= w_reg_324_pp2_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((done1_reg_240 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        done13_3_reg_1259 <= done13_3_fu_629_p2;
        o10_3_reg_1249 <= o10_3_fu_616_p3;
        w12_1_reg_1254 <= w12_1_fu_623_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        done1_reg_240_pp0_iter1_reg <= done1_reg_240;
        done1_reg_240_pp0_iter2_reg <= done1_reg_240_pp0_iter1_reg;
        done1_reg_240_pp0_iter3_reg <= done1_reg_240_pp0_iter2_reg;
        done1_reg_240_pp0_iter4_reg <= done1_reg_240_pp0_iter3_reg;
        done1_reg_240_pp0_iter5_reg <= done1_reg_240_pp0_iter4_reg;
        w7_reg_228_pp0_iter1_reg <= w7_reg_228;
        w7_reg_228_pp0_iter2_reg <= w7_reg_228_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((done4_reg_288 == 1'd0) & (1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        done4_3_reg_1353 <= done4_3_fu_845_p2;
        o1_3_reg_1343 <= o1_3_fu_832_p3;
        w3_1_reg_1348 <= w3_1_fu_839_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        done4_reg_288_pp1_iter1_reg <= done4_reg_288;
        done4_reg_288_pp1_iter2_reg <= done4_reg_288_pp1_iter1_reg;
        done4_reg_288_pp1_iter3_reg <= done4_reg_288_pp1_iter2_reg;
        done4_reg_288_pp1_iter4_reg <= done4_reg_288_pp1_iter3_reg;
        done4_reg_288_pp1_iter5_reg <= done4_reg_288_pp1_iter4_reg;
        w3_reg_276_pp1_iter1_reg <= w3_reg_276;
        w3_reg_276_pp1_iter2_reg <= w3_reg_276_pp1_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        done_reg_336_pp2_iter1_reg <= done_reg_336;
        w_reg_324_pp2_iter1_reg <= w_reg_324;
    end
end

always @ (posedge ap_clk) begin
    if (((done1_reg_240 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        h11_2_reg_1244 <= h11_2_fu_590_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((done4_reg_288 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001))) begin
        h2_2_reg_1338 <= h2_2_fu_806_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_done_phi_fu_340_p4 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        h_6_reg_1393 <= h_6_fu_959_p2;
        tmp_241_reg_1386 <= tmp_241_fu_954_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_done4_phi_fu_292_p4 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        h_7_reg_1308 <= h_7_fu_759_p2;
        tmp_218_reg_1292 <= tmp_218_fu_743_p2;
        tmp_234_reg_1297 <= tmp_234_fu_748_p2;
        w_7_reg_1302 <= w_7_fu_753_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_done1_phi_fu_244_p4 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        h_8_reg_1214 <= h_8_fu_543_p2;
        tmp_229_reg_1198 <= tmp_229_fu_527_p2;
        tmp_237_reg_1203 <= tmp_237_fu_532_p2;
        w_8_reg_1208 <= w_8_fu_537_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001))) begin
        o1_reg_252_pp1_iter1_reg <= o1_reg_252;
        o1_reg_252_pp1_iter2_reg <= o1_reg_252_pp1_iter1_reg;
        o1_reg_252_pp1_iter3_reg <= o1_reg_252_pp1_iter2_reg;
        o1_reg_252_pp1_iter4_reg <= o1_reg_252_pp1_iter3_reg;
        sel_tmp20_reg_1314_pp1_iter1_reg <= sel_tmp20_reg_1314;
        sel_tmp20_reg_1314_pp1_iter2_reg <= sel_tmp20_reg_1314_pp1_iter1_reg;
        sel_tmp20_reg_1314_pp1_iter3_reg <= sel_tmp20_reg_1314_pp1_iter2_reg;
        sel_tmp20_reg_1314_pp1_iter4_reg <= sel_tmp20_reg_1314_pp1_iter3_reg;
        sel_tmp20_reg_1314_pp1_iter5_reg <= sel_tmp20_reg_1314_pp1_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        o7_reg_204_pp0_iter1_reg <= o7_reg_204;
        o7_reg_204_pp0_iter2_reg <= o7_reg_204_pp0_iter1_reg;
        o7_reg_204_pp0_iter3_reg <= o7_reg_204_pp0_iter2_reg;
        o7_reg_204_pp0_iter4_reg <= o7_reg_204_pp0_iter3_reg;
        sel_tmp28_reg_1220_pp0_iter1_reg <= sel_tmp28_reg_1220;
        sel_tmp28_reg_1220_pp0_iter2_reg <= sel_tmp28_reg_1220_pp0_iter1_reg;
        sel_tmp28_reg_1220_pp0_iter3_reg <= sel_tmp28_reg_1220_pp0_iter2_reg;
        sel_tmp28_reg_1220_pp0_iter4_reg <= sel_tmp28_reg_1220_pp0_iter3_reg;
        sel_tmp28_reg_1220_pp0_iter5_reg <= sel_tmp28_reg_1220_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((done_reg_336 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        o_3_reg_1404 <= o_3_fu_1014_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((done4_reg_288 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001))) begin
        o_8_reg_1326 <= o_8_fu_787_p2;
        sel_tmp20_reg_1314 <= sel_tmp20_fu_773_p2;
        sel_tmp24_reg_1332 <= sel_tmp24_fu_793_p2;
        tmp_243_reg_1320 <= tmp_243_fu_779_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((done1_reg_240 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        o_9_reg_1232 <= o_9_fu_571_p2;
        sel_tmp28_reg_1220 <= sel_tmp28_fu_557_p2;
        sel_tmp29_reg_1238 <= sel_tmp29_fu_577_p2;
        tmp_245_reg_1226 <= tmp_245_fu_563_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((done1_reg_240_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((done4_reg_288_pp1_iter5_reg == 1'd0) & (1'b0 == ap_block_pp1_stage2_11001) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage2)))) begin
        reg_368 <= fifo_cout_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((done_reg_336_pp2_iter6_reg == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        tmp_204_reg_1419 <= grp_fu_973_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((done_reg_336_pp2_iter7_reg == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        tmp_205_reg_1424 <= tmp_205_fu_1041_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((done_reg_336_pp2_iter14_reg == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        tmp_206_reg_1429 <= grp_fu_1046_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((done4_reg_288_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_212_reg_1358 <= grp_fu_738_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((write_2_fu_422_p3 == 2'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_213_cast_reg_1188[12 : 0] <= tmp_213_cast_fu_514_p1[12 : 0];
        tmp_331_reg_1167[30 : 0] <= tmp_331_fu_468_p1[30 : 0];
        tmp_332_reg_1173[30 : 0] <= tmp_332_fu_482_p1[30 : 0];
        tmp_333_reg_1178[30 : 0] <= tmp_333_fu_496_p1[30 : 0];
        tmp_334_reg_1183[30 : 0] <= tmp_334_fu_510_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((done4_reg_288_pp1_iter2_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001))) begin
        tmp_213_reg_1363 <= tmp_213_fu_850_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((done4_reg_288_pp1_iter4_reg == 1'd0) & (1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2))) begin
        tmp_214_reg_1368 <= grp_fu_855_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((write_2_fu_422_p3 == 2'd2) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_218_cast_reg_1162[12 : 0] <= tmp_218_cast_fu_454_p1[12 : 0];
        tmp_532_reg_1142[31 : 1] <= tmp_532_fu_430_p2[31 : 1];
        tmp_533_reg_1147[31 : 1] <= tmp_533_fu_436_p2[31 : 1];
        tmp_534_reg_1152[31 : 1] <= tmp_534_fu_442_p2[31 : 1];
        tmp_535_reg_1157[31 : 1] <= tmp_535_fu_448_p2[31 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((done1_reg_240_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_220_reg_1264 <= grp_fu_522_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((done1_reg_240_pp0_iter2_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp_224_reg_1269 <= tmp_224_fu_639_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((done1_reg_240_pp0_iter4_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_225_reg_1274 <= grp_fu_645_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((write_2_fu_422_p3 == 2'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_cast_reg_1193[12 : 0] <= tmp_cast_fu_518_p1[12 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_done_phi_fu_340_p4 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        w_1_reg_1399 <= w_1_fu_965_p3;
    end
end

always @ (*) begin
    if ((ap_phi_mux_done1_phi_fu_244_p4 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_phi_mux_done4_phi_fu_292_p4 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state22 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state22 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_phi_mux_done_phi_fu_340_p4 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state41 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state41 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter5 == 1'b0) & (ap_enable_reg_pp1_iter6 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter21 == 1'b0) & (ap_enable_reg_pp2_iter18 == 1'b0) & (ap_enable_reg_pp2_iter17 == 1'b0) & (ap_enable_reg_pp2_iter16 == 1'b0) & (ap_enable_reg_pp2_iter15 == 1'b0) & (ap_enable_reg_pp2_iter14 == 1'b0) & (ap_enable_reg_pp2_iter13 == 1'b0) & (ap_enable_reg_pp2_iter12 == 1'b0) & (ap_enable_reg_pp2_iter11 == 1'b0) & (ap_enable_reg_pp2_iter10 == 1'b0) & (ap_enable_reg_pp2_iter9 == 1'b0) & (ap_enable_reg_pp2_iter8 == 1'b0) & (ap_enable_reg_pp2_iter7 == 1'b0) & (ap_enable_reg_pp2_iter6 == 1'b0) & (ap_enable_reg_pp2_iter5 == 1'b0) & (ap_enable_reg_pp2_iter4 == 1'b0) & (ap_enable_reg_pp2_iter3 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b0) & (ap_enable_reg_pp2_iter20 == 1'b0) & (ap_enable_reg_pp2_iter19 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((done1_reg_240 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_done1_phi_fu_244_p4 = done13_3_reg_1259;
    end else begin
        ap_phi_mux_done1_phi_fu_244_p4 = done1_reg_240;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (done4_reg_288 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_done4_phi_fu_292_p4 = done4_3_reg_1353;
    end else begin
        ap_phi_mux_done4_phi_fu_292_p4 = done4_reg_288;
    end
end

always @ (*) begin
    if (((done_reg_336 == 1'd0) & (1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_done_phi_fu_340_p4 = done_3_fu_1035_p2;
    end else begin
        ap_phi_mux_done_phi_fu_340_p4 = done_reg_336;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (done4_reg_288 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_h2_phi_fu_268_p4 = h2_2_reg_1338;
    end else begin
        ap_phi_mux_h2_phi_fu_268_p4 = h2_reg_264;
    end
end

always @ (*) begin
    if (((done1_reg_240 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_h7_phi_fu_220_p4 = h11_2_reg_1244;
    end else begin
        ap_phi_mux_h7_phi_fu_220_p4 = h7_reg_216;
    end
end

always @ (*) begin
    if (((done_reg_336 == 1'd0) & (1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_h_phi_fu_316_p4 = h_2_fu_1028_p3;
    end else begin
        ap_phi_mux_h_phi_fu_316_p4 = h_reg_312;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (done4_reg_288_pp1_iter1_reg == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        ap_phi_mux_o1_phi_fu_256_p4 = o1_3_reg_1343;
    end else begin
        ap_phi_mux_o1_phi_fu_256_p4 = o1_reg_252;
    end
end

always @ (*) begin
    if (((done1_reg_240_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_mux_o7_phi_fu_208_p4 = o10_3_reg_1249;
    end else begin
        ap_phi_mux_o7_phi_fu_208_p4 = o7_reg_204;
    end
end

always @ (*) begin
    if (((done_reg_336_pp2_iter1_reg == 1'd0) & (1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter2 == 1'b1))) begin
        ap_phi_mux_o_phi_fu_304_p4 = o_3_reg_1404;
    end else begin
        ap_phi_mux_o_phi_fu_304_p4 = o_reg_300;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (done4_reg_288 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_w3_phi_fu_280_p4 = w3_1_reg_1348;
    end else begin
        ap_phi_mux_w3_phi_fu_280_p4 = w3_reg_276;
    end
end

always @ (*) begin
    if (((done1_reg_240 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_w7_phi_fu_232_p4 = w12_1_reg_1254;
    end else begin
        ap_phi_mux_w7_phi_fu_232_p4 = w7_reg_228;
    end
end

always @ (*) begin
    if (((done_reg_336 == 1'd0) & (1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_w_phi_fu_328_p4 = w_1_reg_1399;
    end else begin
        ap_phi_mux_w_phi_fu_328_p4 = w_reg_324;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter17 == 1'b1))) begin
        cout_burst_buf_V_address0 = cout_burst_buf_V_add_reg_1434;
    end else if ((((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        cout_burst_buf_V_address0 = cout_burst_buf_V_add_1_reg_1373;
    end else if ((((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        cout_burst_buf_V_address0 = cout_burst_buf_V_add_2_reg_1279;
    end else begin
        cout_burst_buf_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp1_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001)) | ((1'b0 == ap_block_pp1_stage2_11001) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage2)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter18 == 1'b1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter17 == 1'b1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter19 == 1'b1)) | ((ap_enable_reg_pp1_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        cout_burst_buf_V_ce0 = 1'b1;
    end else begin
        cout_burst_buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter21 == 1'b1))) begin
        cout_burst_buf_V_ce1 = 1'b1;
    end else begin
        cout_burst_buf_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        cout_burst_buf_V_d0 = p_Result_1_fu_939_p3;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cout_burst_buf_V_d0 = p_Result_2_fu_729_p3;
    end else begin
        cout_burst_buf_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((done1_reg_240_pp0_iter5_reg == 1'd0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((done4_reg_288_pp1_iter5_reg == 1'd0) & (ap_enable_reg_pp1_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        cout_burst_buf_V_we0 = 1'b1;
    end else begin
        cout_burst_buf_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((done_reg_336_pp2_iter20_reg == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter21 == 1'b1))) begin
        cout_burst_buf_V_we1 = 1'b1;
    end else begin
        cout_burst_buf_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2) & (done1_reg_240_pp0_iter5_reg == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp1_stage2) & (done4_reg_288_pp1_iter5_reg == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage2)) | ((done_reg_336_pp2_iter19_reg == 1'd0) & (1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter20 == 1'b1)))) begin
        fifo_cout_V_V_blk_n = fifo_cout_V_V_empty_n;
    end else begin
        fifo_cout_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((done1_reg_240_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((done4_reg_288_pp1_iter5_reg == 1'd0) & (1'b0 == ap_block_pp1_stage2_11001) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage2)) | ((done_reg_336_pp2_iter19_reg == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter20 == 1'b1)))) begin
        fifo_cout_V_V_read = 1'b1;
    end else begin
        fifo_cout_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        grp_fu_1046_ce = 1'b1;
    end else begin
        grp_fu_1046_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        grp_fu_522_ce = 1'b1;
    end else begin
        grp_fu_522_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        grp_fu_645_ce = 1'b1;
    end else begin
        grp_fu_645_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2)) | ((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001)))) begin
        grp_fu_738_ce = 1'b1;
    end else begin
        grp_fu_738_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2)) | ((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001)))) begin
        grp_fu_855_ce = 1'b1;
    end else begin
        grp_fu_855_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        grp_fu_973_ce = 1'b1;
    end else begin
        grp_fu_973_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((write_2_fu_422_p3 == 2'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((write_2_fu_422_p3 == 2'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((write_2_fu_422_p3 == 2'd2) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((write_2_fu_422_p3 == 2'd3) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_phi_mux_done1_phi_fu_244_p4 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter5 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if ((((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_phi_mux_done1_phi_fu_244_p4 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter5 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_phi_mux_done4_phi_fu_292_p4 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1)) & ~((ap_enable_reg_pp1_iter5 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end else if ((((ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_phi_mux_done4_phi_fu_292_p4 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((ap_enable_reg_pp1_iter5 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_pp1_stage1 : begin
            if ((1'b0 == ap_block_pp1_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end
        end
        ap_ST_fsm_pp1_stage2 : begin
            if ((1'b0 == ap_block_pp1_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage2;
            end
        end
        ap_ST_fsm_pp2_stage0 : begin
            if ((~((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter1 == 1'b0) & (ap_phi_mux_done_phi_fu_340_p4 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter20 == 1'b0) & (ap_enable_reg_pp2_iter21 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if ((((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter20 == 1'b0) & (ap_enable_reg_pp2_iter21 == 1'b1)) | ((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter1 == 1'b0) & (ap_phi_mux_done_phi_fu_340_p4 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LAYER_OUT_NUM_T_cast_fu_372_p1 = LAYER_OUT_NUM_T;

assign POOL_ODD_not_fu_402_p0 = POOL_ODD;

assign POOL_ODD_not_fu_402_p2 = (1'd1 ^ POOL_ODD_not_fu_402_p0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp1_stage1 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp1_stage2 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_pp0 = (((ap_ST_fsm_pp0_stage2 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage2_subdone)) | ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone)) | ((ap_ST_fsm_pp0_stage1 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage1_subdone)));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((done1_reg_240_pp0_iter5_reg == 1'd0) & (fifo_cout_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((done1_reg_240_pp0_iter5_reg == 1'd0) & (fifo_cout_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_block_pp1 = (((1'b1 == ap_block_pp1_stage2_subdone) & (ap_ST_fsm_pp1_stage2 == ap_CS_fsm)) | ((ap_ST_fsm_pp1_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp1_stage0_subdone)) | ((ap_ST_fsm_pp1_stage1 == ap_CS_fsm) & (1'b1 == ap_block_pp1_stage1_subdone)));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage2_11001 = ((done4_reg_288_pp1_iter5_reg == 1'd0) & (fifo_cout_V_V_empty_n == 1'b0) & (ap_enable_reg_pp1_iter5 == 1'b1));
end

always @ (*) begin
    ap_block_pp1_stage2_subdone = ((done4_reg_288_pp1_iter5_reg == 1'd0) & (fifo_cout_V_V_empty_n == 1'b0) & (ap_enable_reg_pp1_iter5 == 1'b1));
end

always @ (*) begin
    ap_block_pp2 = ((1'b1 == ap_block_pp2_stage0_subdone) & (ap_ST_fsm_pp2_stage0 == ap_CS_fsm));
end

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage0_11001 = ((done_reg_336_pp2_iter19_reg == 1'd0) & (fifo_cout_V_V_empty_n == 1'b0) & (ap_enable_reg_pp2_iter20 == 1'b1));
end

always @ (*) begin
    ap_block_pp2_stage0_subdone = ((done_reg_336_pp2_iter19_reg == 1'd0) & (fifo_cout_V_V_empty_n == 1'b0) & (ap_enable_reg_pp2_iter20 == 1'b1));
end

assign ap_block_state10_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage2_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state19_pp0_stage2_iter5 = ((done1_reg_240_pp0_iter5_reg == 1'd0) & (fifo_cout_V_V_empty_n == 1'b0));
end

assign ap_block_state20_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp1_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp1_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp1_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp1_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp1_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp1_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp1_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp1_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp1_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp1_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp1_stage2_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp1_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp1_stage1_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state39_pp1_stage2_iter5 = ((done4_reg_288_pp1_iter5_reg == 1'd0) & (fifo_cout_V_V_empty_n == 1'b0));
end

assign ap_block_state3_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp1_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp2_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp2_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp2_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp2_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp2_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state48_pp2_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp2_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state50_pp2_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state51_pp2_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state52_pp2_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state53_pp2_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state54_pp2_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state55_pp2_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state56_pp2_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state57_pp2_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state58_pp2_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state59_pp2_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state60_pp2_stage0_iter19 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state61_pp2_stage0_iter20 = ((done_reg_336_pp2_iter19_reg == 1'd0) & (fifo_cout_V_V_empty_n == 1'b0));
end

assign ap_block_state62_pp2_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_enable_operation_277 = (done_reg_336_pp2_iter16_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_279 = (done_reg_336_pp2_iter18_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_288 = (done_reg_336_pp2_iter20_reg == 1'd0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

always @ (*) begin
    ap_enable_state58_pp2_iter17_stage0 = ((ap_enable_reg_pp2_iter17 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0));
end

always @ (*) begin
    ap_enable_state60_pp2_iter19_stage0 = ((ap_enable_reg_pp2_iter19 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0));
end

always @ (*) begin
    ap_enable_state62_pp2_iter21_stage0 = ((ap_enable_reg_pp2_iter21 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0));
end

assign brmerge1_fu_388_p0 = POOL_ODD;

assign brmerge1_fu_388_p2 = (brmerge_not_fu_382_p2 | brmerge1_fu_388_p0);

assign brmerge_fu_376_p0 = en;

assign brmerge_fu_376_p1 = up_sample;

assign brmerge_fu_376_p2 = (brmerge_fu_376_p1 | brmerge_fu_376_p0);

assign brmerge_not_fu_382_p2 = (brmerge_fu_376_p2 ^ 1'd1);

assign cout_buf_0_V_11_fu_708_p3 = ((tmp_545_reg_1284[0:0] === 1'b1) ? cout_buf_0_V_9_fu_683_p1 : reg_368);

assign cout_buf_0_V_13_fu_1094_p3 = ((tmp_538_reg_1440_pp2_iter19_reg[0:0] === 1'b1) ? cout_buf_0_V_reg_1446 : fifo_cout_V_V_dout);

assign cout_buf_0_V_14_fu_932_p3 = ((sel_tmp20_reg_1314_pp1_iter5_reg[0:0] === 1'b1) ? cout_buf_0_V_7_fu_918_p3 : cout_buf_0_V_4_fu_904_p3);

assign cout_buf_0_V_15_fu_722_p3 = ((sel_tmp28_reg_1220_pp0_iter5_reg[0:0] === 1'b1) ? cout_buf_0_V_11_fu_708_p3 : cout_buf_0_V_6_fu_694_p3);

assign cout_buf_0_V_3_fu_893_p1 = cout_burst_buf_V_q0[255:0];

assign cout_buf_0_V_4_fu_904_p3 = ((tmp_541_reg_1378[0:0] === 1'b1) ? cout_buf_0_V_3_fu_893_p1 : 256'd0);

assign cout_buf_0_V_6_fu_694_p3 = ((tmp_545_reg_1284[0:0] === 1'b1) ? cout_buf_0_V_9_fu_683_p1 : 256'd0);

assign cout_buf_0_V_7_fu_918_p3 = ((tmp_541_reg_1378[0:0] === 1'b1) ? cout_buf_0_V_3_fu_893_p1 : reg_368);

assign cout_buf_0_V_9_fu_683_p1 = cout_burst_buf_V_q0[255:0];

assign cout_buf_0_V_fu_1084_p1 = cout_burst_buf_V_q0[255:0];

assign cout_buf_1_V_11_fu_701_p3 = ((tmp_545_reg_1284[0:0] === 1'b1) ? reg_368 : grp_fu_358_p4);

assign cout_buf_1_V_13_fu_1088_p3 = ((tmp_538_reg_1440_pp2_iter19_reg[0:0] === 1'b1) ? fifo_cout_V_V_dout : cout_buf_1_V_reg_1451);

assign cout_buf_1_V_14_fu_925_p3 = ((sel_tmp20_reg_1314_pp1_iter5_reg[0:0] === 1'b1) ? cout_buf_1_V_8_fu_911_p3 : cout_buf_1_V_5_fu_897_p3);

assign cout_buf_1_V_15_fu_715_p3 = ((sel_tmp28_reg_1220_pp0_iter5_reg[0:0] === 1'b1) ? cout_buf_1_V_11_fu_701_p3 : cout_buf_1_V_6_fu_687_p3);

assign cout_buf_1_V_5_fu_897_p3 = ((tmp_541_reg_1378[0:0] === 1'b1) ? 256'd0 : grp_fu_358_p4);

assign cout_buf_1_V_6_fu_687_p3 = ((tmp_545_reg_1284[0:0] === 1'b1) ? 256'd0 : grp_fu_358_p4);

assign cout_buf_1_V_8_fu_911_p3 = ((tmp_541_reg_1378[0:0] === 1'b1) ? reg_368 : grp_fu_358_p4);

assign cout_burst_buf_V_address1 = cout_burst_buf_V_add_reg_1434_pp2_iter20_reg;

assign cout_burst_buf_V_d1 = {{cout_buf_1_V_13_reg_1456}, {cout_buf_0_V_13_reg_1461}};

assign done13_3_fu_629_p2 = (tmp_251_fu_598_p2 & sel_tmp29_reg_1238);

assign done4_3_fu_845_p2 = (tmp_250_fu_814_p2 & sel_tmp24_reg_1332);

assign done_3_fu_1035_p2 = (tmp_249_fu_988_p2 & sel_tmp4_fu_1001_p2);

assign grp_fu_1046_p1 = LAYER_OUT_NUM_T_cast_reg_1131;

assign grp_fu_348_p4 = {{LAYER_OUT_NUM_T[15:3]}};

assign grp_fu_358_p4 = {{cout_burst_buf_V_q0[511:256]}};

assign grp_fu_645_p1 = LAYER_OUT_NUM_T_cast_reg_1131;

assign grp_fu_738_p0 = tmp_331_reg_1167;

assign grp_fu_855_p1 = LAYER_OUT_NUM_T_cast_reg_1131;

assign h11_2_fu_590_p3 = ((tmp_245_fu_563_p2[0:0] === 1'b1) ? sel_tmp31_fu_583_p3 : h7_reg_216);

assign h2_2_fu_806_p3 = ((tmp_243_fu_779_p2[0:0] === 1'b1) ? sel_tmp27_fu_799_p3 : h2_reg_264);

assign h_2_fu_1028_p3 = ((tmp_241_reg_1386[0:0] === 1'b1) ? sel_tmp9_fu_1021_p3 : h_reg_312);

assign h_6_fu_959_p2 = ($signed(32'd1) + $signed(ap_phi_mux_h_phi_fu_316_p4));

assign h_7_fu_759_p2 = ($signed(32'd1) + $signed(ap_phi_mux_h2_phi_fu_268_p4));

assign h_8_fu_543_p2 = ($signed(32'd1) + $signed(ap_phi_mux_h7_phi_fu_220_p4));

assign local_cout_idx_1_fu_865_p2 = (tmp_539_fu_859_p2 + tmp_214_reg_1368);

assign local_cout_idx_2_fu_655_p2 = (tmp_543_fu_649_p2 + tmp_225_reg_1274);

assign local_cout_idx_fu_1056_p2 = (tmp_536_fu_1050_p2 + tmp_206_reg_1429);

assign o10_3_fu_616_p3 = ((tmp_245_reg_1226[0:0] === 1'b1) ? sel_tmp30_fu_609_p3 : o7_reg_204);

assign o1_3_fu_832_p3 = ((tmp_243_reg_1320[0:0] === 1'b1) ? sel_tmp25_fu_825_p3 : o1_reg_252);

assign o_3_fu_1014_p3 = ((tmp_241_reg_1386[0:0] === 1'b1) ? sel_tmp5_fu_1006_p3 : ap_phi_mux_o_phi_fu_304_p4);

assign o_7_fu_982_p2 = (32'd1 + ap_phi_mux_o_phi_fu_304_p4);

assign o_8_fu_787_p2 = (32'd1 + ap_phi_mux_o1_phi_fu_256_p4);

assign o_9_fu_571_p2 = (32'd1 + ap_phi_mux_o7_phi_fu_208_p4);

assign p_1_fu_993_p3 = ((tmp_249_fu_988_p2[0:0] === 1'b1) ? 32'd0 : o_7_fu_982_p2);

assign p_2_fu_818_p3 = ((tmp_250_fu_814_p2[0:0] === 1'b1) ? 32'd0 : o_8_reg_1326);

assign p_3_fu_602_p3 = ((tmp_251_fu_598_p2[0:0] === 1'b1) ? 32'd0 : o_9_reg_1232);

assign p_Result_1_fu_939_p3 = {{cout_buf_1_V_14_fu_925_p3}, {cout_buf_0_V_14_fu_932_p3}};

assign p_Result_2_fu_729_p3 = {{cout_buf_1_V_15_fu_715_p3}, {cout_buf_0_V_15_fu_722_p3}};

assign p_s_fu_394_p0 = up_sample;

assign p_s_fu_394_p3 = ((p_s_fu_394_p0[0:0] === 1'b1) ? 2'd2 : 2'd0);

assign sel_tmp20_fu_773_p2 = (tmp_235_fu_769_p2 & tmp_219_fu_765_p2);

assign sel_tmp24_fu_793_p2 = (tmp_247_fu_783_p2 & tmp_243_fu_779_p2);

assign sel_tmp25_fu_825_p3 = ((sel_tmp24_reg_1332[0:0] === 1'b1) ? p_2_fu_818_p3 : o1_reg_252);

assign sel_tmp26_fu_414_p3 = ((sel_tmp_fu_408_p2[0:0] === 1'b1) ? p_s_fu_394_p3 : 2'd1);

assign sel_tmp27_fu_799_p3 = ((sel_tmp24_fu_793_p2[0:0] === 1'b1) ? 32'd0 : h_7_reg_1308);

assign sel_tmp28_fu_557_p2 = (tmp_238_fu_553_p2 & tmp_230_fu_549_p2);

assign sel_tmp29_fu_577_p2 = (tmp_248_fu_567_p2 & tmp_245_fu_563_p2);

assign sel_tmp30_fu_609_p3 = ((sel_tmp29_reg_1238[0:0] === 1'b1) ? p_3_fu_602_p3 : o7_reg_204);

assign sel_tmp31_fu_583_p3 = ((sel_tmp29_fu_577_p2[0:0] === 1'b1) ? 32'd0 : h_8_reg_1214);

assign sel_tmp4_fu_1001_p2 = (tmp_246_fu_978_p2 & tmp_241_reg_1386);

assign sel_tmp5_fu_1006_p3 = ((sel_tmp4_fu_1001_p2[0:0] === 1'b1) ? p_1_fu_993_p3 : ap_phi_mux_o_phi_fu_304_p4);

assign sel_tmp9_fu_1021_p3 = ((sel_tmp4_fu_1001_p2[0:0] === 1'b1) ? 32'd0 : h_6_reg_1393);

assign sel_tmp_fu_408_p0 = up_sample;

assign sel_tmp_fu_408_p2 = (sel_tmp_fu_408_p0 & POOL_ODD_not_fu_402_p2);

assign tmp_195_fu_472_p4 = {{in_h_iter[31:1]}};

assign tmp_196_fu_486_p4 = {{in_w_iter[31:1]}};

assign tmp_197_fu_500_p4 = {{LAYER_IN_H_T[31:1]}};

assign tmp_205_fu_1041_p2 = (w_reg_324_pp2_iter7_reg + tmp_204_reg_1419);

assign tmp_208_fu_1061_p4 = {{local_cout_idx_fu_1056_p2[31:4]}};

assign tmp_209_fu_1071_p1 = tmp_208_fu_1061_p4;

assign tmp_213_cast_fu_514_p1 = grp_fu_348_p4;

assign tmp_213_fu_850_p2 = (w3_reg_276_pp1_iter2_reg + tmp_212_reg_1358);

assign tmp_216_fu_870_p4 = {{local_cout_idx_1_fu_865_p2[31:4]}};

assign tmp_217_fu_880_p1 = tmp_216_fu_870_p4;

assign tmp_218_cast_fu_454_p1 = grp_fu_348_p4;

assign tmp_218_fu_743_p2 = ($signed(tmp_332_reg_1173) + $signed(ap_phi_mux_h2_phi_fu_268_p4));

assign tmp_219_fu_765_p2 = ((tmp_218_reg_1292 < LAYER_OUT_H) ? 1'b1 : 1'b0);

assign tmp_224_fu_639_p2 = (w7_reg_228_pp0_iter2_reg + tmp_542_fu_634_p2);

assign tmp_227_fu_660_p4 = {{local_cout_idx_2_fu_655_p2[31:4]}};

assign tmp_228_fu_670_p1 = tmp_227_fu_660_p4;

assign tmp_229_fu_527_p2 = ($signed(tmp_533_reg_1147) + $signed(ap_phi_mux_h7_phi_fu_220_p4));

assign tmp_230_fu_549_p2 = ((tmp_229_reg_1198 < LAYER_OUT_H) ? 1'b1 : 1'b0);

assign tmp_234_fu_748_p2 = (ap_phi_mux_w3_phi_fu_280_p4 + tmp_333_reg_1178);

assign tmp_235_fu_769_p2 = ((tmp_234_reg_1297 < LAYER_OUT_W) ? 1'b1 : 1'b0);

assign tmp_237_fu_532_p2 = (ap_phi_mux_w7_phi_fu_232_p4 + tmp_534_reg_1152);

assign tmp_238_fu_553_p2 = ((tmp_237_reg_1203 < LAYER_OUT_W) ? 1'b1 : 1'b0);

assign tmp_241_fu_954_p1 = LAYER_IN_W_T;

assign tmp_241_fu_954_p2 = ((w_6_fu_948_p2 == tmp_241_fu_954_p1) ? 1'b1 : 1'b0);

assign tmp_243_fu_779_p2 = ((w_7_reg_1302 == tmp_331_reg_1167) ? 1'b1 : 1'b0);

assign tmp_245_fu_563_p2 = ((w_8_reg_1208 == tmp_532_reg_1142) ? 1'b1 : 1'b0);

assign tmp_246_fu_978_p2 = ((h_6_reg_1393 == LAYER_IN_H_T) ? 1'b1 : 1'b0);

assign tmp_247_fu_783_p2 = ((h_7_reg_1308 == tmp_334_reg_1183) ? 1'b1 : 1'b0);

assign tmp_248_fu_567_p2 = ((h_8_reg_1214 == tmp_535_reg_1157) ? 1'b1 : 1'b0);

assign tmp_249_fu_988_p2 = ((o_7_fu_982_p2 == tmp_cast_reg_1193) ? 1'b1 : 1'b0);

assign tmp_250_fu_814_p2 = ((o_8_reg_1326 == tmp_213_cast_reg_1188) ? 1'b1 : 1'b0);

assign tmp_251_fu_598_p2 = ((o_9_reg_1232 == tmp_218_cast_reg_1162) ? 1'b1 : 1'b0);

assign tmp_331_fu_468_p1 = tmp_s_fu_458_p4;

assign tmp_332_fu_482_p1 = tmp_195_fu_472_p4;

assign tmp_333_fu_496_p1 = tmp_196_fu_486_p4;

assign tmp_334_fu_510_p1 = tmp_197_fu_500_p4;

assign tmp_532_fu_430_p0 = LAYER_IN_W_T;

assign tmp_532_fu_430_p2 = tmp_532_fu_430_p0 << 32'd1;

assign tmp_533_fu_436_p2 = in_h_iter << 32'd1;

assign tmp_534_fu_442_p2 = in_w_iter << 32'd1;

assign tmp_535_fu_448_p2 = LAYER_IN_H_T << 32'd1;

assign tmp_536_fu_1050_p2 = o_reg_300_pp2_iter15_reg << 32'd3;

assign tmp_539_fu_859_p2 = o1_reg_252_pp1_iter4_reg << 32'd3;

assign tmp_542_fu_634_p2 = tmp_220_reg_1264 << 32'd1;

assign tmp_543_fu_649_p2 = o7_reg_204_pp0_iter4_reg << 32'd3;

assign tmp_cast_fu_518_p1 = grp_fu_348_p4;

assign tmp_s_fu_458_p1 = LAYER_IN_W_T;

assign tmp_s_fu_458_p4 = {{tmp_s_fu_458_p1[31:1]}};

assign w12_1_fu_623_p3 = ((tmp_245_reg_1226[0:0] === 1'b1) ? 32'd0 : w_8_reg_1208);

assign w3_1_fu_839_p3 = ((tmp_243_reg_1320[0:0] === 1'b1) ? 32'd0 : w_7_reg_1302);

assign w_1_fu_965_p3 = ((tmp_241_fu_954_p2[0:0] === 1'b1) ? 32'd0 : w_6_fu_948_p2);

assign w_6_fu_948_p2 = (32'd1 + ap_phi_mux_w_phi_fu_328_p4);

assign w_7_fu_753_p2 = (32'd1 + ap_phi_mux_w3_phi_fu_280_p4);

assign w_8_fu_537_p2 = (32'd1 + ap_phi_mux_w7_phi_fu_232_p4);

assign write_2_fu_422_p3 = ((brmerge1_fu_388_p2[0:0] === 1'b1) ? 2'd0 : sel_tmp26_fu_414_p3);

always @ (posedge ap_clk) begin
    LAYER_OUT_NUM_T_cast_reg_1131[31:16] <= 16'b0000000000000000;
    tmp_532_reg_1142[0] <= 1'b0;
    tmp_533_reg_1147[0] <= 1'b0;
    tmp_534_reg_1152[0] <= 1'b0;
    tmp_535_reg_1157[0] <= 1'b0;
    tmp_218_cast_reg_1162[31:13] <= 19'b0000000000000000000;
    tmp_331_reg_1167[31] <= 1'b0;
    tmp_332_reg_1173[31] <= 1'b0;
    tmp_333_reg_1178[31] <= 1'b0;
    tmp_334_reg_1183[31] <= 1'b0;
    tmp_213_cast_reg_1188[31:13] <= 19'b0000000000000000000;
    tmp_cast_reg_1193[31:13] <= 19'b0000000000000000000;
end

endmodule //cout_write_fifo_read
