// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cout_write (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        fifo_cout_V_V_dout,
        fifo_cout_V_V_empty_n,
        fifo_cout_V_V_read,
        fifo_config_in_V_V_dout,
        fifo_config_in_V_V_empty_n,
        fifo_config_in_V_V_read,
        m_axi_global_cout_V_AWVALID,
        m_axi_global_cout_V_AWREADY,
        m_axi_global_cout_V_AWADDR,
        m_axi_global_cout_V_AWID,
        m_axi_global_cout_V_AWLEN,
        m_axi_global_cout_V_AWSIZE,
        m_axi_global_cout_V_AWBURST,
        m_axi_global_cout_V_AWLOCK,
        m_axi_global_cout_V_AWCACHE,
        m_axi_global_cout_V_AWPROT,
        m_axi_global_cout_V_AWQOS,
        m_axi_global_cout_V_AWREGION,
        m_axi_global_cout_V_AWUSER,
        m_axi_global_cout_V_WVALID,
        m_axi_global_cout_V_WREADY,
        m_axi_global_cout_V_WDATA,
        m_axi_global_cout_V_WSTRB,
        m_axi_global_cout_V_WLAST,
        m_axi_global_cout_V_WID,
        m_axi_global_cout_V_WUSER,
        m_axi_global_cout_V_ARVALID,
        m_axi_global_cout_V_ARREADY,
        m_axi_global_cout_V_ARADDR,
        m_axi_global_cout_V_ARID,
        m_axi_global_cout_V_ARLEN,
        m_axi_global_cout_V_ARSIZE,
        m_axi_global_cout_V_ARBURST,
        m_axi_global_cout_V_ARLOCK,
        m_axi_global_cout_V_ARCACHE,
        m_axi_global_cout_V_ARPROT,
        m_axi_global_cout_V_ARQOS,
        m_axi_global_cout_V_ARREGION,
        m_axi_global_cout_V_ARUSER,
        m_axi_global_cout_V_RVALID,
        m_axi_global_cout_V_RREADY,
        m_axi_global_cout_V_RDATA,
        m_axi_global_cout_V_RLAST,
        m_axi_global_cout_V_RID,
        m_axi_global_cout_V_RUSER,
        m_axi_global_cout_V_RRESP,
        m_axi_global_cout_V_BVALID,
        m_axi_global_cout_V_BREADY,
        m_axi_global_cout_V_BRESP,
        m_axi_global_cout_V_BID,
        m_axi_global_cout_V_BUSER,
        global_cout_V_offset_dout,
        global_cout_V_offset_empty_n,
        global_cout_V_offset_read
);

parameter    ap_ST_fsm_state1 = 65'd1;
parameter    ap_ST_fsm_state2 = 65'd2;
parameter    ap_ST_fsm_state3 = 65'd4;
parameter    ap_ST_fsm_state4 = 65'd8;
parameter    ap_ST_fsm_state5 = 65'd16;
parameter    ap_ST_fsm_state6 = 65'd32;
parameter    ap_ST_fsm_state7 = 65'd64;
parameter    ap_ST_fsm_state8 = 65'd128;
parameter    ap_ST_fsm_state9 = 65'd256;
parameter    ap_ST_fsm_state10 = 65'd512;
parameter    ap_ST_fsm_state11 = 65'd1024;
parameter    ap_ST_fsm_state12 = 65'd2048;
parameter    ap_ST_fsm_state13 = 65'd4096;
parameter    ap_ST_fsm_state14 = 65'd8192;
parameter    ap_ST_fsm_state15 = 65'd16384;
parameter    ap_ST_fsm_state16 = 65'd32768;
parameter    ap_ST_fsm_state17 = 65'd65536;
parameter    ap_ST_fsm_state18 = 65'd131072;
parameter    ap_ST_fsm_state19 = 65'd262144;
parameter    ap_ST_fsm_state20 = 65'd524288;
parameter    ap_ST_fsm_state21 = 65'd1048576;
parameter    ap_ST_fsm_state22 = 65'd2097152;
parameter    ap_ST_fsm_state23 = 65'd4194304;
parameter    ap_ST_fsm_state24 = 65'd8388608;
parameter    ap_ST_fsm_state25 = 65'd16777216;
parameter    ap_ST_fsm_state26 = 65'd33554432;
parameter    ap_ST_fsm_state27 = 65'd67108864;
parameter    ap_ST_fsm_state28 = 65'd134217728;
parameter    ap_ST_fsm_state29 = 65'd268435456;
parameter    ap_ST_fsm_state30 = 65'd536870912;
parameter    ap_ST_fsm_state31 = 65'd1073741824;
parameter    ap_ST_fsm_state32 = 65'd2147483648;
parameter    ap_ST_fsm_state33 = 65'd4294967296;
parameter    ap_ST_fsm_state34 = 65'd8589934592;
parameter    ap_ST_fsm_state35 = 65'd17179869184;
parameter    ap_ST_fsm_state36 = 65'd34359738368;
parameter    ap_ST_fsm_state37 = 65'd68719476736;
parameter    ap_ST_fsm_state38 = 65'd137438953472;
parameter    ap_ST_fsm_state39 = 65'd274877906944;
parameter    ap_ST_fsm_state40 = 65'd549755813888;
parameter    ap_ST_fsm_state41 = 65'd1099511627776;
parameter    ap_ST_fsm_state42 = 65'd2199023255552;
parameter    ap_ST_fsm_state43 = 65'd4398046511104;
parameter    ap_ST_fsm_state44 = 65'd8796093022208;
parameter    ap_ST_fsm_state45 = 65'd17592186044416;
parameter    ap_ST_fsm_state46 = 65'd35184372088832;
parameter    ap_ST_fsm_state47 = 65'd70368744177664;
parameter    ap_ST_fsm_state48 = 65'd140737488355328;
parameter    ap_ST_fsm_state49 = 65'd281474976710656;
parameter    ap_ST_fsm_state50 = 65'd562949953421312;
parameter    ap_ST_fsm_state51 = 65'd1125899906842624;
parameter    ap_ST_fsm_state52 = 65'd2251799813685248;
parameter    ap_ST_fsm_state53 = 65'd4503599627370496;
parameter    ap_ST_fsm_state54 = 65'd9007199254740992;
parameter    ap_ST_fsm_state55 = 65'd18014398509481984;
parameter    ap_ST_fsm_state56 = 65'd36028797018963968;
parameter    ap_ST_fsm_state57 = 65'd72057594037927936;
parameter    ap_ST_fsm_state58 = 65'd144115188075855872;
parameter    ap_ST_fsm_state59 = 65'd288230376151711744;
parameter    ap_ST_fsm_state60 = 65'd576460752303423488;
parameter    ap_ST_fsm_state61 = 65'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 65'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 65'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 65'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 65'd18446744073709551616;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [255:0] fifo_cout_V_V_dout;
input   fifo_cout_V_V_empty_n;
output   fifo_cout_V_V_read;
input  [191:0] fifo_config_in_V_V_dout;
input   fifo_config_in_V_V_empty_n;
output   fifo_config_in_V_V_read;
output   m_axi_global_cout_V_AWVALID;
input   m_axi_global_cout_V_AWREADY;
output  [63:0] m_axi_global_cout_V_AWADDR;
output  [0:0] m_axi_global_cout_V_AWID;
output  [31:0] m_axi_global_cout_V_AWLEN;
output  [2:0] m_axi_global_cout_V_AWSIZE;
output  [1:0] m_axi_global_cout_V_AWBURST;
output  [1:0] m_axi_global_cout_V_AWLOCK;
output  [3:0] m_axi_global_cout_V_AWCACHE;
output  [2:0] m_axi_global_cout_V_AWPROT;
output  [3:0] m_axi_global_cout_V_AWQOS;
output  [3:0] m_axi_global_cout_V_AWREGION;
output  [0:0] m_axi_global_cout_V_AWUSER;
output   m_axi_global_cout_V_WVALID;
input   m_axi_global_cout_V_WREADY;
output  [511:0] m_axi_global_cout_V_WDATA;
output  [63:0] m_axi_global_cout_V_WSTRB;
output   m_axi_global_cout_V_WLAST;
output  [0:0] m_axi_global_cout_V_WID;
output  [0:0] m_axi_global_cout_V_WUSER;
output   m_axi_global_cout_V_ARVALID;
input   m_axi_global_cout_V_ARREADY;
output  [63:0] m_axi_global_cout_V_ARADDR;
output  [0:0] m_axi_global_cout_V_ARID;
output  [31:0] m_axi_global_cout_V_ARLEN;
output  [2:0] m_axi_global_cout_V_ARSIZE;
output  [1:0] m_axi_global_cout_V_ARBURST;
output  [1:0] m_axi_global_cout_V_ARLOCK;
output  [3:0] m_axi_global_cout_V_ARCACHE;
output  [2:0] m_axi_global_cout_V_ARPROT;
output  [3:0] m_axi_global_cout_V_ARQOS;
output  [3:0] m_axi_global_cout_V_ARREGION;
output  [0:0] m_axi_global_cout_V_ARUSER;
input   m_axi_global_cout_V_RVALID;
output   m_axi_global_cout_V_RREADY;
input  [511:0] m_axi_global_cout_V_RDATA;
input   m_axi_global_cout_V_RLAST;
input  [0:0] m_axi_global_cout_V_RID;
input  [0:0] m_axi_global_cout_V_RUSER;
input  [1:0] m_axi_global_cout_V_RRESP;
input   m_axi_global_cout_V_BVALID;
output   m_axi_global_cout_V_BREADY;
input  [1:0] m_axi_global_cout_V_BRESP;
input  [0:0] m_axi_global_cout_V_BID;
input  [0:0] m_axi_global_cout_V_BUSER;
input  [57:0] global_cout_V_offset_dout;
input   global_cout_V_offset_empty_n;
output   global_cout_V_offset_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg fifo_cout_V_V_read;
reg fifo_config_in_V_V_read;
reg m_axi_global_cout_V_AWVALID;
reg m_axi_global_cout_V_WVALID;
reg m_axi_global_cout_V_BREADY;
reg global_cout_V_offset_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [64:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    fifo_config_in_V_V_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire   [0:0] ap_phi_mux_done_i_i_phi_fu_266_p4;
wire   [0:0] ap_phi_mux_layer_start_i_i_phi_fu_254_p4;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg   [0:0] layer_start_i_i_reg_250;
reg    global_cout_V_offset_blk_n;
reg   [31:0] reg_560;
reg    ap_predicate_op139_read_state6;
reg    ap_block_state6;
wire    ap_CS_fsm_state13;
reg   [31:0] reg_565;
wire   [0:0] ap_phi_mux_p_0961_i_i_phi_fu_242_p4;
wire    ap_CS_fsm_state11;
wire   [0:0] tmp_311_i_i_fu_997_p2;
wire   [0:0] tmp_312_i_i_fu_1003_p2;
reg   [31:0] reg_570;
reg   [31:0] reg_575;
reg   [31:0] reg_580;
reg   [31:0] reg_585;
reg   [31:0] reg_590;
reg   [31:0] reg_595;
reg   [31:0] reg_600;
reg   [31:0] reg_605;
reg   [31:0] reg_610;
reg   [31:0] reg_615;
reg   [31:0] reg_620;
reg   [31:0] reg_625;
wire   [31:0] grp_fu_525_p2;
reg   [31:0] reg_630;
reg   [0:0] brmerge_i_i_reg_1640;
reg   [0:0] tmp_306_i_i_reg_1537;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state60;
wire   [0:0] tmp_314_i_i_fu_1254_p2;
wire   [31:0] grp_fu_530_p2;
reg   [31:0] reg_634;
wire    ap_CS_fsm_state14;
wire   [0:0] grp_fu_642_p2;
wire    ap_CS_fsm_state54;
reg   [0:0] tmp_320_i_i_reg_1676;
wire    ap_CS_fsm_state61;
wire   [31:0] grp_fu_542_p2;
reg   [31:0] reg_638;
wire    ap_CS_fsm_state16;
wire   [0:0] tmp_329_i_i_fu_1133_p2;
wire    ap_CS_fsm_state62;
wire   [0:0] grp_fu_652_p2;
reg   [57:0] global_cout_V_offset_10_reg_1456;
reg    ap_block_state1;
reg   [31:0] LAYER_BATCH_V_reg_1461;
reg   [31:0] num_tile_prev_2_reg_1467;
wire   [0:0] tmp_fu_740_p1;
reg   [0:0] tmp_reg_1473;
reg   [0:0] change_layout_prev_l_1_reg_1477;
reg   [0:0] up_sample_prev_load_reg_1482;
reg   [0:0] en_prev_load_reg_1487;
reg   [191:0] p_Val2_17_reg_1492;
reg    ap_block_state10;
reg   [31:0] COUT_OFFSET_V_reg_1497;
reg   [15:0] LAYER_IN_NUM_T_V_reg_1502;
reg   [15:0] LAYER_OUT_NUM_T_V_reg_1507;
reg   [31:0] LAYER_IN_H_T_V_reg_1515;
reg   [31:0] LAYER_IN_W_T_V_reg_1524;
reg   [0:0] tmp_540_reg_1532;
wire   [0:0] tmp_306_i_i_fu_818_p2;
wire   [0:0] en_fu_832_p2;
reg   [0:0] en_reg_1541;
wire   [0:0] max_pool_fu_848_p2;
reg   [0:0] max_pool_reg_1547;
reg   [0:0] up_sample_reg_1552;
wire   [31:0] LAYER_OUT_H_HW_V_fu_868_p4;
reg   [31:0] LAYER_OUT_H_HW_V_reg_1559;
wire   [31:0] LAYER_OUT_W_HW_V_fu_878_p4;
reg   [31:0] LAYER_OUT_W_HW_V_reg_1564;
wire   [31:0] LAYER_IN_NUM_V_fu_888_p1;
reg   [31:0] LAYER_IN_NUM_V_reg_1570;
reg   [31:0] LAYER_OUT_NUM_V_reg_1575;
reg   [31:0] LAYER_IN_H_V_reg_1581;
reg   [31:0] LAYER_IN_W_V_reg_1587;
wire   [31:0] LAYER_OUT_H_V_fu_922_p4;
reg   [31:0] LAYER_OUT_H_V_reg_1592;
wire   [31:0] LAYER_OUT_W_V_fu_933_p4;
reg   [31:0] LAYER_OUT_W_V_reg_1597;
wire   [0:0] p_Result_s_fu_951_p2;
reg   [0:0] p_Result_s_reg_1602;
wire   [0:0] change_layout_fu_991_p2;
reg   [0:0] change_layout_reg_1607;
reg   [0:0] tmp_311_i_i_reg_1612;
reg   [0:0] tmp_312_i_i_reg_1616;
reg   [31:0] in_w_iter_prev_load_reg_1620;
reg   [0:0] change_layout_prev_l_reg_1625;
reg   [0:0] up_sample_prev_load_1_reg_1630;
reg   [0:0] en_prev_load_1_reg_1635;
wire   [0:0] brmerge_i_i_fu_1089_p2;
wire    ap_CS_fsm_state12;
wire    grp_cout_write_fifo_read_fu_394_ap_ready;
wire    grp_cout_write_fifo_read_fu_394_ap_done;
reg    ap_predicate_op231_call_state12;
wire    grp_cout_write_ddr_write_fu_371_ap_ready;
wire    grp_cout_write_ddr_write_fu_371_ap_done;
reg    ap_predicate_op232_call_state12;
reg    ap_predicate_op234_call_state12;
reg    ap_predicate_op235_call_state12;
reg    ap_predicate_op238_call_state12;
reg    ap_block_state12_on_subcall_done;
wire   [0:0] tmp_318_i_i_fu_1110_p2;
reg   [0:0] tmp_318_i_i_reg_1644;
wire   [31:0] num_iter_fu_1118_p2;
reg   [31:0] num_iter_reg_1649;
wire   [31:0] num_iter_2_fu_1127_p2;
reg   [31:0] num_iter_2_reg_1661;
wire    ap_CS_fsm_state15;
wire   [0:0] grp_fu_662_p2;
reg   [0:0] tmp_331_i_i_reg_1670;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state53;
wire   [31:0] num_tile_2_fu_1153_p2;
reg   [31:0] num_tile_2_reg_1685;
wire   [31:0] grp_fu_1093_p2;
reg   [31:0] ret_V_reg_1692;
wire   [31:0] p_4_i_i_61_fu_1165_p2;
reg   [31:0] p_4_i_i_61_reg_1697;
wire   [31:0] num_tile_1_i_i_fu_1200_p3;
reg   [31:0] num_tile_1_i_i_reg_1703;
wire   [31:0] ind_w_2_i_i_fu_1207_p3;
reg   [31:0] ind_w_2_i_i_reg_1708;
wire   [31:0] ind_w_t_3_i_i_fu_1215_p3;
reg   [31:0] ind_w_t_3_i_i_reg_1713;
reg   [0:0] tmp_323_i_i_reg_1718;
wire    ap_CS_fsm_state55;
wire   [31:0] num_iter_1_fu_1225_p2;
reg   [31:0] num_iter_1_reg_1722;
wire   [0:0] tmp_327_i_i_fu_1231_p2;
reg   [0:0] tmp_327_i_i_reg_1728;
wire    ap_CS_fsm_state56;
reg   [31:0] layer_iter_4_reg_1732;
wire   [0:0] tmp_330_i_i_fu_1239_p2;
reg   [0:0] tmp_330_i_i_reg_1738;
wire    ap_CS_fsm_state57;
reg   [0:0] tmp_325_i_i_reg_1753;
wire    ap_CS_fsm_state63;
reg   [11:0] cout_burst_buf_ping_s_address0;
reg    cout_burst_buf_ping_s_ce0;
reg    cout_burst_buf_ping_s_we0;
wire   [511:0] cout_burst_buf_ping_s_q0;
reg    cout_burst_buf_ping_s_ce1;
reg    cout_burst_buf_ping_s_we1;
reg   [11:0] cout_burst_buf_pong_s_address0;
reg    cout_burst_buf_pong_s_ce0;
reg    cout_burst_buf_pong_s_we0;
wire   [511:0] cout_burst_buf_pong_s_q0;
reg    cout_burst_buf_pong_s_ce1;
reg    cout_burst_buf_pong_s_we1;
wire    grp_cout_write_ddr_write_fu_371_ap_start;
wire    grp_cout_write_ddr_write_fu_371_ap_idle;
wire   [11:0] grp_cout_write_ddr_write_fu_371_cout_burst_buf_V_address0;
wire    grp_cout_write_ddr_write_fu_371_cout_burst_buf_V_ce0;
reg   [511:0] grp_cout_write_ddr_write_fu_371_cout_burst_buf_V_q0;
wire    grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWVALID;
wire   [63:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWADDR;
wire   [0:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWID;
wire   [31:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWLEN;
wire   [2:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWSIZE;
wire   [1:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWBURST;
wire   [1:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWLOCK;
wire   [3:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWCACHE;
wire   [2:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWPROT;
wire   [3:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWQOS;
wire   [3:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWREGION;
wire   [0:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWUSER;
wire    grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_WVALID;
wire   [511:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_WDATA;
wire   [63:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_WSTRB;
wire    grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_WLAST;
wire   [0:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_WID;
wire   [0:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_WUSER;
wire    grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARVALID;
wire   [63:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARADDR;
wire   [0:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARID;
wire   [31:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARLEN;
wire   [2:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARSIZE;
wire   [1:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARBURST;
wire   [1:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARLOCK;
wire   [3:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARCACHE;
wire   [2:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARPROT;
wire   [3:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARQOS;
wire   [3:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARREGION;
wire   [0:0] grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARUSER;
wire    grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_RREADY;
wire    grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_BREADY;
reg    grp_cout_write_ddr_write_fu_371_en;
reg    grp_cout_write_ddr_write_fu_371_up_sample;
reg    grp_cout_write_ddr_write_fu_371_change_layout;
wire    grp_cout_write_fifo_read_fu_394_ap_start;
wire    grp_cout_write_fifo_read_fu_394_ap_idle;
wire   [11:0] grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_address0;
wire    grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_ce0;
wire    grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_we0;
wire   [511:0] grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_d0;
reg   [511:0] grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_q0;
wire   [11:0] grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_address1;
wire    grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_ce1;
wire    grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_we1;
wire   [511:0] grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_d1;
wire    grp_cout_write_fifo_read_fu_394_fifo_cout_V_V_read;
wire    grp_cout_write_fifo_read_fu_394_en;
wire    grp_cout_write_fifo_read_fu_394_up_sample;
reg   [0:0] p_0961_i_i_reg_238;
wire    ap_CS_fsm_state58;
reg   [0:0] ap_phi_mux_layer_start_i_i_be_phi_fu_291_p24;
reg   [0:0] done_i_i_reg_262;
reg   [0:0] ap_phi_mux_done_i_i_be_phi_fu_335_p24;
reg   [0:0] layer_start_1_i_i_reg_273;
reg   [0:0] layer_start_i_i_be_reg_286;
wire    ap_CS_fsm_state59;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state64;
reg   [0:0] done_i_i_be_reg_330;
reg    grp_cout_write_ddr_write_fu_371_ap_start_reg;
reg    ap_block_state6_ignore_call0;
wire    ap_CS_fsm_state65;
reg    grp_cout_write_fifo_read_fu_394_ap_start_reg;
reg   [31:0] layer_iter_i_i_fu_110;
wire   [31:0] p_5_i_i_fu_1141_p3;
wire   [31:0] p_6_i_i_fu_1243_p3;
wire   [31:0] p_4_i_i_fu_1262_p3;
reg   [31:0] ind_w_t_prev_fu_114;
reg   [31:0] ind_w_prev_fu_118;
reg   [31:0] in_w_iter_prev_fu_122;
reg   [31:0] num_iter_prev_fu_126;
reg   [0:0] change_layout_prev_fu_130;
reg   [31:0] ind_w_prev_1_fu_134;
reg   [31:0] ind_w_t_prev_1_fu_138;
reg   [31:0] num_tile_prev_fu_142;
reg   [31:0] num_tile_prev_1_fu_146;
reg   [31:0] num_tile_fu_150;
wire   [31:0] task_cnt_fu_1009_p2;
reg   [31:0] cout_offset_prev_fu_154;
reg   [31:0] LAYER_OUT_W_HW_prev_fu_158;
reg   [31:0] LAYER_OUT_H_HW_prev_fu_162;
reg   [31:0] LAYER_IN_W_T_prev_fu_166;
reg   [31:0] LAYER_IN_H_T_prev_fu_170;
reg   [31:0] LAYER_OUT_NUM_T_prev_fu_174;
wire   [31:0] LAYER_OUT_NUM_T_prev_1_fu_1015_p1;
reg   [0:0] up_sample_prev_fu_178;
reg   [0:0] en_prev_fu_182;
reg   [31:0] in_w_iter_prev_1_fu_186;
reg   [31:0] in_h_iter_prev_fu_190;
reg   [31:0] in_h_iter_prev_1_fu_194;
reg   [31:0] num_iter_prev_1_fu_198;
reg   [191:0] tmp_V_fu_202;
reg   [191:0] tmp_V_67_fu_206;
reg   [191:0] tmp_V_68_fu_210;
reg   [191:0] tmp_V_69_fu_214;
wire   [31:0] STRIDE_V_fu_760_p4;
wire   [0:0] tmp_541_fu_824_p3;
wire   [1:0] tmp_542_fu_838_p4;
wire   [9:0] tmp_i_i_fu_944_p3;
wire   [0:0] tmp_307_i_i_fu_957_p2;
wire   [0:0] tmp_308_i_i_fu_963_p2;
wire   [0:0] tmp_309_i_i_fu_974_p2;
wire   [0:0] tmp_310_i_i_fu_980_p2;
wire   [0:0] or_cond_i_i_fu_968_p2;
wire   [0:0] p_i_i_fu_985_p2;
wire   [30:0] tmp_317_i_i_fu_1097_p4;
wire   [31:0] tmp_354_i_i_fu_1106_p1;
wire   [31:0] tmp_313_i_i_fu_1115_p1;
wire   [31:0] tmp_328_i_i_fu_1124_p1;
wire   [31:0] p_1713_v_cast_cast_ca_fu_1158_p3;
wire   [0:0] tmp_319_i_i_fu_1175_p2;
wire   [31:0] ind_w_fu_1180_p2;
wire   [0:0] tmp_316_i_i_fu_1171_p2;
wire   [31:0] p_ind_w_i_i_fu_1185_p3;
wire   [31:0] p_i_i_62_fu_1193_p3;
wire   [31:0] tmp_326_i_i_fu_1222_p1;
reg    grp_fu_1093_ap_start;
wire    grp_fu_1093_ap_done;
reg    ap_predicate_op436_call_state65;
reg    ap_predicate_op438_call_state65;
reg    ap_block_state65_on_subcall_done;
reg   [64:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 65'd1;
#0 grp_cout_write_ddr_write_fu_371_ap_start_reg = 1'b0;
#0 grp_cout_write_fifo_read_fu_394_ap_start_reg = 1'b0;
end

cout_write_cout_bWhU #(
    .DataWidth( 512 ),
    .AddressRange( 4056 ),
    .AddressWidth( 12 ))
cout_burst_buf_ping_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(cout_burst_buf_ping_s_address0),
    .ce0(cout_burst_buf_ping_s_ce0),
    .we0(cout_burst_buf_ping_s_we0),
    .d0(grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_d0),
    .q0(cout_burst_buf_ping_s_q0),
    .address1(grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_address1),
    .ce1(cout_burst_buf_ping_s_ce1),
    .we1(cout_burst_buf_ping_s_we1),
    .d1(grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_d1)
);

cout_write_cout_bWhU #(
    .DataWidth( 512 ),
    .AddressRange( 4056 ),
    .AddressWidth( 12 ))
cout_burst_buf_pong_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(cout_burst_buf_pong_s_address0),
    .ce0(cout_burst_buf_pong_s_ce0),
    .we0(cout_burst_buf_pong_s_we0),
    .d0(grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_d0),
    .q0(cout_burst_buf_pong_s_q0),
    .address1(grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_address1),
    .ce1(cout_burst_buf_pong_s_ce1),
    .we1(cout_burst_buf_pong_s_we1),
    .d1(grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_d1)
);

cout_write_ddr_write grp_cout_write_ddr_write_fu_371(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cout_write_ddr_write_fu_371_ap_start),
    .ap_done(grp_cout_write_ddr_write_fu_371_ap_done),
    .ap_idle(grp_cout_write_ddr_write_fu_371_ap_idle),
    .ap_ready(grp_cout_write_ddr_write_fu_371_ap_ready),
    .cout_burst_buf_V_address0(grp_cout_write_ddr_write_fu_371_cout_burst_buf_V_address0),
    .cout_burst_buf_V_ce0(grp_cout_write_ddr_write_fu_371_cout_burst_buf_V_ce0),
    .cout_burst_buf_V_q0(grp_cout_write_ddr_write_fu_371_cout_burst_buf_V_q0),
    .m_axi_global_cout_V_AWVALID(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWVALID),
    .m_axi_global_cout_V_AWREADY(m_axi_global_cout_V_AWREADY),
    .m_axi_global_cout_V_AWADDR(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWADDR),
    .m_axi_global_cout_V_AWID(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWID),
    .m_axi_global_cout_V_AWLEN(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWLEN),
    .m_axi_global_cout_V_AWSIZE(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWSIZE),
    .m_axi_global_cout_V_AWBURST(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWBURST),
    .m_axi_global_cout_V_AWLOCK(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWLOCK),
    .m_axi_global_cout_V_AWCACHE(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWCACHE),
    .m_axi_global_cout_V_AWPROT(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWPROT),
    .m_axi_global_cout_V_AWQOS(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWQOS),
    .m_axi_global_cout_V_AWREGION(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWREGION),
    .m_axi_global_cout_V_AWUSER(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWUSER),
    .m_axi_global_cout_V_WVALID(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_WVALID),
    .m_axi_global_cout_V_WREADY(m_axi_global_cout_V_WREADY),
    .m_axi_global_cout_V_WDATA(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_WDATA),
    .m_axi_global_cout_V_WSTRB(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_WSTRB),
    .m_axi_global_cout_V_WLAST(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_WLAST),
    .m_axi_global_cout_V_WID(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_WID),
    .m_axi_global_cout_V_WUSER(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_WUSER),
    .m_axi_global_cout_V_ARVALID(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARVALID),
    .m_axi_global_cout_V_ARREADY(1'b0),
    .m_axi_global_cout_V_ARADDR(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARADDR),
    .m_axi_global_cout_V_ARID(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARID),
    .m_axi_global_cout_V_ARLEN(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARLEN),
    .m_axi_global_cout_V_ARSIZE(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARSIZE),
    .m_axi_global_cout_V_ARBURST(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARBURST),
    .m_axi_global_cout_V_ARLOCK(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARLOCK),
    .m_axi_global_cout_V_ARCACHE(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARCACHE),
    .m_axi_global_cout_V_ARPROT(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARPROT),
    .m_axi_global_cout_V_ARQOS(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARQOS),
    .m_axi_global_cout_V_ARREGION(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARREGION),
    .m_axi_global_cout_V_ARUSER(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_ARUSER),
    .m_axi_global_cout_V_RVALID(1'b0),
    .m_axi_global_cout_V_RREADY(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_RREADY),
    .m_axi_global_cout_V_RDATA(512'd0),
    .m_axi_global_cout_V_RLAST(1'b0),
    .m_axi_global_cout_V_RID(1'd0),
    .m_axi_global_cout_V_RUSER(1'd0),
    .m_axi_global_cout_V_RRESP(2'd0),
    .m_axi_global_cout_V_BVALID(m_axi_global_cout_V_BVALID),
    .m_axi_global_cout_V_BREADY(grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_BREADY),
    .m_axi_global_cout_V_BRESP(m_axi_global_cout_V_BRESP),
    .m_axi_global_cout_V_BID(m_axi_global_cout_V_BID),
    .m_axi_global_cout_V_BUSER(m_axi_global_cout_V_BUSER),
    .global_cout_V_offset(global_cout_V_offset_10_reg_1456),
    .en(grp_cout_write_ddr_write_fu_371_en),
    .up_sample(grp_cout_write_ddr_write_fu_371_up_sample),
    .num_iter(reg_620),
    .in_h_iter(reg_615),
    .in_w_iter(reg_610),
    .LAYER_OUT_NUM_T(reg_605),
    .LAYER_IN_H_T(reg_600),
    .LAYER_IN_W_T(reg_595),
    .LAYER_OUT_H_HW(reg_590),
    .LAYER_OUT_W_HW(reg_585),
    .num_tile(reg_575),
    .ind_w_t(reg_570),
    .ind_w(reg_565),
    .cout_offset(reg_580),
    .change_layout(grp_cout_write_ddr_write_fu_371_change_layout)
);

cout_write_fifo_read grp_cout_write_fifo_read_fu_394(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cout_write_fifo_read_fu_394_ap_start),
    .ap_done(grp_cout_write_fifo_read_fu_394_ap_done),
    .ap_idle(grp_cout_write_fifo_read_fu_394_ap_idle),
    .ap_ready(grp_cout_write_fifo_read_fu_394_ap_ready),
    .cout_burst_buf_V_address0(grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_address0),
    .cout_burst_buf_V_ce0(grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_ce0),
    .cout_burst_buf_V_we0(grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_we0),
    .cout_burst_buf_V_d0(grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_d0),
    .cout_burst_buf_V_q0(grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_q0),
    .cout_burst_buf_V_address1(grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_address1),
    .cout_burst_buf_V_ce1(grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_ce1),
    .cout_burst_buf_V_we1(grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_we1),
    .cout_burst_buf_V_d1(grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_d1),
    .fifo_cout_V_V_dout(fifo_cout_V_V_dout),
    .fifo_cout_V_V_empty_n(fifo_cout_V_V_empty_n),
    .fifo_cout_V_V_read(grp_cout_write_fifo_read_fu_394_fifo_cout_V_V_read),
    .en(grp_cout_write_fifo_read_fu_394_en),
    .up_sample(grp_cout_write_fifo_read_fu_394_up_sample),
    .LAYER_OUT_H(LAYER_OUT_H_V_reg_1592),
    .LAYER_OUT_W(LAYER_OUT_W_V_reg_1597),
    .LAYER_OUT_NUM_T(LAYER_OUT_NUM_T_V_reg_1507),
    .LAYER_IN_H_T(LAYER_IN_H_T_V_reg_1515),
    .LAYER_IN_W_T(LAYER_IN_W_T_V_reg_1524),
    .in_h_iter(reg_625),
    .in_w_iter(in_w_iter_prev_load_reg_1620)
);

top_kernel_udiv_3kbM #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
top_kernel_udiv_3kbM_U347(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_1093_ap_start),
    .done(grp_fu_1093_ap_done),
    .din0(LAYER_IN_H_V_reg_1581),
    .din1(LAYER_IN_H_T_V_reg_1515),
    .ce(1'b1),
    .dout(grp_fu_1093_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state65) & (1'b0 == ap_block_state65_on_subcall_done))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cout_write_ddr_write_fu_371_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_state11) & (tmp_reg_1473 == 1'd1) & (tmp_311_i_i_fu_997_p2 == 1'd1) & (tmp_312_i_i_fu_1003_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state11) & (tmp_311_i_i_fu_997_p2 == 1'd1) & (tmp_reg_1473 == 1'd0) & (tmp_312_i_i_fu_1003_p2 == 1'd0)) | (~((ap_predicate_op139_read_state6 == 1'b1) & (fifo_config_in_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6) & (tmp_fu_740_p1 == 1'd1) & (ap_phi_mux_done_i_i_phi_fu_266_p4 == 1'd1) & (ap_phi_mux_p_0961_i_i_phi_fu_242_p4 == 1'd0)) | (~((ap_predicate_op139_read_state6 == 1'b1) & (fifo_config_in_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6) & (ap_phi_mux_done_i_i_phi_fu_266_p4 == 1'd1) & (tmp_fu_740_p1 == 1'd0) & (ap_phi_mux_p_0961_i_i_phi_fu_242_p4 == 1'd0)))) begin
            grp_cout_write_ddr_write_fu_371_ap_start_reg <= 1'b1;
        end else if ((grp_cout_write_ddr_write_fu_371_ap_ready == 1'b1)) begin
            grp_cout_write_ddr_write_fu_371_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cout_write_fifo_read_fu_394_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_state11) & (tmp_312_i_i_fu_1003_p2 == 1'd1) & (tmp_311_i_i_fu_997_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state11) & (tmp_reg_1473 == 1'd1) & (tmp_311_i_i_fu_997_p2 == 1'd1) & (tmp_312_i_i_fu_1003_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state11) & (tmp_311_i_i_fu_997_p2 == 1'd1) & (tmp_reg_1473 == 1'd0) & (tmp_312_i_i_fu_1003_p2 == 1'd0)))) begin
            grp_cout_write_fifo_read_fu_394_ap_start_reg <= 1'b1;
        end else if ((grp_cout_write_fifo_read_fu_394_ap_ready == 1'b1)) begin
            grp_cout_write_fifo_read_fu_394_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12) & (tmp_311_i_i_reg_1612 == 1'd1))) begin
        change_layout_prev_fu_130 <= change_layout_reg_1607;
    end else if ((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        change_layout_prev_fu_130 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state64)) begin
        done_i_i_be_reg_330 <= tmp_325_i_i_reg_1753;
    end else if (((1'b1 == ap_CS_fsm_state58) & (tmp_306_i_i_reg_1537 == 1'd1) & (tmp_327_i_i_reg_1728 == 1'd0) & (tmp_323_i_i_reg_1718 == 1'd0) & (tmp_320_i_i_reg_1676 == 1'd0) & (brmerge_i_i_reg_1640 == 1'd0))) begin
        done_i_i_be_reg_330 <= tmp_330_i_i_reg_1738;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        done_i_i_be_reg_330 <= tmp_331_i_i_reg_1670;
    end else if (((1'b1 == ap_CS_fsm_state59) | ((1'b1 == ap_CS_fsm_state56) & (tmp_327_i_i_fu_1231_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state55) & (grp_fu_652_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state15) & (grp_fu_652_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state62) & (grp_fu_652_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state16) & (tmp_329_i_i_fu_1133_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state61) & (grp_fu_642_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state14) & (grp_fu_642_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state60) & (tmp_314_i_i_fu_1254_p2 == 1'd1)))) begin
        done_i_i_be_reg_330 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        done_i_i_reg_262 <= ap_phi_mux_done_i_i_be_phi_fu_335_p24;
    end else if (((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        done_i_i_reg_262 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12) & (tmp_311_i_i_reg_1612 == 1'd1))) begin
        in_h_iter_prev_1_fu_194 <= in_h_iter_prev_fu_190;
    end else if ((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        in_h_iter_prev_1_fu_194 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state61) & (grp_fu_642_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state54) & (tmp_320_i_i_reg_1676 == 1'd1)) | ((1'b1 == ap_CS_fsm_state14) & (grp_fu_642_p2 == 1'd1)))) begin
        in_h_iter_prev_fu_190 <= reg_630;
    end else if (((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state56) & (tmp_327_i_i_fu_1231_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state56) & (tmp_327_i_i_fu_1231_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state55) & (grp_fu_652_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state15) & (grp_fu_652_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state62) & (grp_fu_652_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state62) & (grp_fu_652_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state16) & (tmp_329_i_i_fu_1133_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state16) & (tmp_329_i_i_fu_1133_p2 == 1'd0)))) begin
        in_h_iter_prev_fu_190 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12) & (tmp_311_i_i_reg_1612 == 1'd1))) begin
        in_w_iter_prev_1_fu_186 <= in_w_iter_prev_fu_122;
    end else if ((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        in_w_iter_prev_1_fu_186 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state55) & (grp_fu_652_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state15) & (grp_fu_652_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state62) & (grp_fu_652_p2 == 1'd1)))) begin
        in_w_iter_prev_fu_122 <= reg_634;
    end else if (((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state56) & (tmp_327_i_i_fu_1231_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state56) & (tmp_327_i_i_fu_1231_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state62) & (grp_fu_652_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state16) & (tmp_329_i_i_fu_1133_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state16) & (tmp_329_i_i_fu_1133_p2 == 1'd0)))) begin
        in_w_iter_prev_fu_122 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12) & (tmp_311_i_i_reg_1612 == 1'd1))) begin
        ind_w_prev_1_fu_134 <= ind_w_prev_fu_118;
    end else if ((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ind_w_prev_1_fu_134 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state59) | ((1'b1 == ap_CS_fsm_state56) & (tmp_327_i_i_fu_1231_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state56) & (tmp_327_i_i_fu_1231_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state55) & (grp_fu_652_p2 == 1'd1)))) begin
        ind_w_prev_fu_118 <= ind_w_2_i_i_reg_1708;
    end else if ((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ind_w_prev_fu_118 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12) & (tmp_311_i_i_reg_1612 == 1'd1))) begin
        ind_w_t_prev_1_fu_138 <= ind_w_t_prev_fu_114;
    end else if ((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ind_w_t_prev_1_fu_138 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state59) | ((1'b1 == ap_CS_fsm_state56) & (tmp_327_i_i_fu_1231_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state56) & (tmp_327_i_i_fu_1231_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state55) & (grp_fu_652_p2 == 1'd1)))) begin
        ind_w_t_prev_fu_114 <= ind_w_t_3_i_i_reg_1713;
    end else if ((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ind_w_t_prev_fu_114 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state64)) begin
        layer_iter_i_i_fu_110 <= p_4_i_i_fu_1262_p3;
    end else if (((1'b1 == ap_CS_fsm_state58) & (tmp_306_i_i_reg_1537 == 1'd1) & (tmp_327_i_i_reg_1728 == 1'd0) & (tmp_323_i_i_reg_1718 == 1'd0) & (tmp_320_i_i_reg_1676 == 1'd0) & (brmerge_i_i_reg_1640 == 1'd0))) begin
        layer_iter_i_i_fu_110 <= p_6_i_i_fu_1243_p3;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_iter_i_i_fu_110 <= p_5_i_i_fu_1141_p3;
    end else if ((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer_iter_i_i_fu_110 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op139_read_state6 == 1'b1) & (fifo_config_in_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6) & (ap_phi_mux_layer_start_i_i_phi_fu_254_p4 == 1'd0) & (done_i_i_reg_262 == 1'd0))) begin
        layer_start_1_i_i_reg_273 <= layer_start_i_i_reg_250;
    end else if ((~((fifo_config_in_V_V_empty_n == 1'b0) & (layer_start_i_i_reg_250 == 1'd1)) & (1'b1 == ap_CS_fsm_state10) & (layer_start_i_i_reg_250 == 1'd1))) begin
        layer_start_1_i_i_reg_273 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state18) | ((1'b1 == ap_CS_fsm_state58) & (tmp_306_i_i_reg_1537 == 1'd1) & (tmp_327_i_i_reg_1728 == 1'd0) & (tmp_323_i_i_reg_1718 == 1'd0) & (tmp_320_i_i_reg_1676 == 1'd0) & (brmerge_i_i_reg_1640 == 1'd0)))) begin
        layer_start_i_i_be_reg_286 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state59) | ((1'b1 == ap_CS_fsm_state56) & (tmp_327_i_i_fu_1231_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state55) & (grp_fu_652_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state15) & (grp_fu_652_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state62) & (grp_fu_652_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state16) & (tmp_329_i_i_fu_1133_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state61) & (grp_fu_642_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state14) & (grp_fu_642_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state60) & (tmp_314_i_i_fu_1254_p2 == 1'd1)))) begin
        layer_start_i_i_be_reg_286 <= layer_start_1_i_i_reg_273;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        layer_start_i_i_reg_250 <= ap_phi_mux_layer_start_i_i_be_phi_fu_291_p24;
    end else if (((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        layer_start_i_i_reg_250 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12) & (tmp_311_i_i_reg_1612 == 1'd1))) begin
        num_iter_prev_1_fu_198 <= num_iter_prev_fu_126;
    end else if ((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_iter_prev_1_fu_198 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state60) & (tmp_314_i_i_fu_1254_p2 == 1'd1))) begin
        num_iter_prev_fu_126 <= num_iter_reg_1649;
    end else if (((1'b1 == ap_CS_fsm_state56) & (tmp_327_i_i_fu_1231_p2 == 1'd1))) begin
        num_iter_prev_fu_126 <= num_iter_1_reg_1722;
    end else if (((1'b1 == ap_CS_fsm_state16) & (tmp_329_i_i_fu_1133_p2 == 1'd1))) begin
        num_iter_prev_fu_126 <= num_iter_2_reg_1661;
    end else if (((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state56) & (tmp_327_i_i_fu_1231_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state62) & (grp_fu_652_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state62) & (grp_fu_652_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state16) & (tmp_329_i_i_fu_1133_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state61) & (grp_fu_642_p2 == 1'd1)))) begin
        num_iter_prev_fu_126 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12) & (tmp_311_i_i_reg_1612 == 1'd1))) begin
        num_tile_fu_150 <= task_cnt_fu_1009_p2;
    end else if ((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_tile_fu_150 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state59) | ((1'b1 == ap_CS_fsm_state56) & (tmp_327_i_i_fu_1231_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state56) & (tmp_327_i_i_fu_1231_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state55) & (grp_fu_652_p2 == 1'd1)))) begin
        num_tile_prev_1_fu_146 <= num_tile_1_i_i_reg_1703;
    end else if ((((1'b1 == ap_CS_fsm_state15) & (grp_fu_652_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state62) & (grp_fu_652_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state62) & (grp_fu_652_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state16) & (tmp_329_i_i_fu_1133_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state16) & (tmp_329_i_i_fu_1133_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state61) & (grp_fu_642_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state14) & (grp_fu_642_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state60) & (tmp_314_i_i_fu_1254_p2 == 1'd1)))) begin
        num_tile_prev_1_fu_146 <= reg_560;
    end else if ((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_tile_prev_1_fu_146 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12) & (tmp_311_i_i_reg_1612 == 1'd1))) begin
        num_tile_prev_fu_142 <= num_tile_prev_2_reg_1467;
    end else if ((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_tile_prev_fu_142 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((fifo_config_in_V_V_empty_n == 1'b0) & (layer_start_i_i_reg_250 == 1'd1)) & (1'b1 == ap_CS_fsm_state10))) begin
        COUT_OFFSET_V_reg_1497 <= {{tmp_V_68_fu_210[127:96]}};
        LAYER_IN_H_T_V_reg_1515 <= {{tmp_V_69_fu_214[127:96]}};
        LAYER_IN_NUM_T_V_reg_1502 <= {{tmp_V_69_fu_214[79:64]}};
        LAYER_IN_W_T_V_reg_1524 <= {{tmp_V_69_fu_214[159:128]}};
        LAYER_OUT_NUM_T_V_reg_1507 <= {{tmp_V_69_fu_214[95:80]}};
        en_reg_1541 <= en_fu_832_p2;
        max_pool_reg_1547 <= max_pool_fu_848_p2;
        p_Val2_17_reg_1492 <= tmp_V_69_fu_214;
        tmp_306_i_i_reg_1537 <= tmp_306_i_i_fu_818_p2;
        tmp_540_reg_1532 <= tmp_V_69_fu_214[32'd9];
        up_sample_reg_1552 <= tmp_V_69_fu_214[32'd6];
    end
end

always @ (posedge ap_clk) begin
    if (((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        LAYER_BATCH_V_reg_1461 <= {{fifo_config_in_V_V_dout[191:160]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12) & (tmp_311_i_i_reg_1612 == 1'd1))) begin
        LAYER_IN_H_T_prev_fu_170 <= LAYER_IN_H_T_V_reg_1515;
        LAYER_IN_W_T_prev_fu_166 <= LAYER_IN_W_T_V_reg_1524;
        LAYER_OUT_H_HW_prev_fu_162 <= LAYER_OUT_H_HW_V_reg_1559;
        LAYER_OUT_NUM_T_prev_fu_174[15 : 0] <= LAYER_OUT_NUM_T_prev_1_fu_1015_p1[15 : 0];
        LAYER_OUT_W_HW_prev_fu_158 <= LAYER_OUT_W_HW_V_reg_1564;
        cout_offset_prev_fu_154 <= COUT_OFFSET_V_reg_1497;
        en_prev_fu_182 <= en_reg_1541;
        up_sample_prev_fu_178 <= up_sample_reg_1552;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        LAYER_IN_H_V_reg_1581 <= {{tmp_V_67_fu_206[95:64]}};
        LAYER_IN_NUM_V_reg_1570 <= LAYER_IN_NUM_V_fu_888_p1;
        LAYER_IN_W_V_reg_1587 <= {{tmp_V_67_fu_206[127:96]}};
        LAYER_OUT_H_HW_V_reg_1559 <= {{tmp_V_fu_202[159:128]}};
        LAYER_OUT_H_V_reg_1592 <= {{tmp_V_67_fu_206[159:128]}};
        LAYER_OUT_NUM_V_reg_1575 <= {{tmp_V_67_fu_206[63:32]}};
        LAYER_OUT_W_HW_V_reg_1564 <= {{tmp_V_fu_202[191:160]}};
        LAYER_OUT_W_V_reg_1597 <= {{tmp_V_67_fu_206[191:160]}};
        change_layout_reg_1607 <= change_layout_fu_991_p2;
        p_Result_s_reg_1602 <= p_Result_s_fu_951_p2;
        tmp_311_i_i_reg_1612 <= tmp_311_i_i_fu_997_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12))) begin
        brmerge_i_i_reg_1640 <= brmerge_i_i_fu_1089_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op139_read_state6 == 1'b1) & (fifo_config_in_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6) & (ap_phi_mux_done_i_i_phi_fu_266_p4 == 1'd1) & (ap_phi_mux_p_0961_i_i_phi_fu_242_p4 == 1'd0))) begin
        change_layout_prev_l_1_reg_1477 <= change_layout_prev_fu_130;
        en_prev_load_reg_1487 <= en_prev_fu_182;
        up_sample_prev_load_reg_1482 <= up_sample_prev_fu_178;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (tmp_311_i_i_fu_997_p2 == 1'd1) & (tmp_312_i_i_fu_1003_p2 == 1'd0))) begin
        change_layout_prev_l_reg_1625 <= change_layout_prev_fu_130;
        en_prev_load_1_reg_1635 <= en_prev_fu_182;
        up_sample_prev_load_1_reg_1630 <= up_sample_prev_fu_178;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        global_cout_V_offset_10_reg_1456 <= global_cout_V_offset_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (tmp_311_i_i_fu_997_p2 == 1'd1))) begin
        in_w_iter_prev_load_reg_1620 <= in_w_iter_prev_fu_122;
        tmp_312_i_i_reg_1616 <= tmp_312_i_i_fu_1003_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state54)) begin
        ind_w_2_i_i_reg_1708 <= ind_w_2_i_i_fu_1207_p3;
        ind_w_t_3_i_i_reg_1713 <= ind_w_t_3_i_i_fu_1215_p3;
        num_tile_1_i_i_reg_1703 <= num_tile_1_i_i_fu_1200_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state56) & (tmp_327_i_i_fu_1231_p2 == 1'd0))) begin
        layer_iter_4_reg_1732 <= grp_fu_542_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state55) & (grp_fu_652_p2 == 1'd0))) begin
        num_iter_1_reg_1722 <= num_iter_1_fu_1225_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state15) & (grp_fu_652_p2 == 1'd0))) begin
        num_iter_2_reg_1661 <= num_iter_2_fu_1127_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (brmerge_i_i_reg_1640 == 1'd1))) begin
        num_iter_reg_1649 <= num_iter_fu_1118_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state53)) begin
        num_tile_2_reg_1685 <= num_tile_2_fu_1153_p2;
        p_4_i_i_61_reg_1697 <= p_4_i_i_61_fu_1165_p2;
        ret_V_reg_1692 <= grp_fu_1093_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op139_read_state6 == 1'b1) & (fifo_config_in_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        num_tile_prev_2_reg_1467 <= num_tile_prev_1_fu_146;
        tmp_reg_1473 <= tmp_fu_740_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        p_0961_i_i_reg_238 <= p_Result_s_reg_1602;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) | (~((ap_predicate_op139_read_state6 == 1'b1) & (fifo_config_in_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)))) begin
        reg_560 <= num_tile_fu_150;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state11) & (tmp_311_i_i_fu_997_p2 == 1'd1) & (tmp_312_i_i_fu_1003_p2 == 1'd0)) | (~((ap_predicate_op139_read_state6 == 1'b1) & (fifo_config_in_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6) & (ap_phi_mux_done_i_i_phi_fu_266_p4 == 1'd1) & (ap_phi_mux_p_0961_i_i_phi_fu_242_p4 == 1'd0)))) begin
        reg_565 <= ind_w_prev_1_fu_134;
        reg_570 <= ind_w_t_prev_1_fu_138;
        reg_575 <= num_tile_prev_fu_142;
        reg_580 <= cout_offset_prev_fu_154;
        reg_585 <= LAYER_OUT_W_HW_prev_fu_158;
        reg_590 <= LAYER_OUT_H_HW_prev_fu_162;
        reg_595 <= LAYER_IN_W_T_prev_fu_166;
        reg_600 <= LAYER_IN_H_T_prev_fu_170;
        reg_605[15 : 0] <= LAYER_OUT_NUM_T_prev_fu_174[15 : 0];
        reg_610 <= in_w_iter_prev_1_fu_186;
        reg_615 <= in_h_iter_prev_1_fu_194;
        reg_620 <= num_iter_prev_1_fu_198;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state11) & (tmp_312_i_i_fu_1003_p2 == 1'd1) & (tmp_311_i_i_fu_997_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state11) & (tmp_311_i_i_fu_997_p2 == 1'd1) & (tmp_312_i_i_fu_1003_p2 == 1'd0)))) begin
        reg_625 <= in_h_iter_prev_fu_190;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state19) | ((1'b1 == ap_CS_fsm_state60) & (tmp_314_i_i_fu_1254_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state13) & (tmp_306_i_i_reg_1537 == 1'd0) & (brmerge_i_i_reg_1640 == 1'd0)))) begin
        reg_630 <= grp_fu_525_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state54) & (tmp_320_i_i_reg_1676 == 1'd0)) | ((1'b1 == ap_CS_fsm_state61) & (grp_fu_642_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state14) & (grp_fu_642_p2 == 1'd0)))) begin
        reg_634 <= grp_fu_530_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state62) & (grp_fu_652_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state16) & (tmp_329_i_i_fu_1133_p2 == 1'd0)))) begin
        reg_638 <= grp_fu_542_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (tmp_306_i_i_reg_1537 == 1'd1) & (brmerge_i_i_reg_1640 == 1'd0))) begin
        tmp_318_i_i_reg_1644 <= tmp_318_i_i_fu_1110_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        tmp_320_i_i_reg_1676 <= grp_fu_642_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        tmp_323_i_i_reg_1718 <= grp_fu_652_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state63)) begin
        tmp_325_i_i_reg_1753 <= grp_fu_662_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        tmp_327_i_i_reg_1728 <= tmp_327_i_i_fu_1231_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        tmp_330_i_i_reg_1738 <= tmp_330_i_i_fu_1239_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        tmp_331_i_i_reg_1670 <= grp_fu_662_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        tmp_V_67_fu_206 <= fifo_config_in_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        tmp_V_68_fu_210 <= fifo_config_in_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state9)) | ((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4)))) begin
        tmp_V_69_fu_214 <= fifo_config_in_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | (~((ap_predicate_op139_read_state6 == 1'b1) & (fifo_config_in_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6) & (layer_start_i_i_reg_250 == 1'd1) & (done_i_i_reg_262 == 1'd0)))) begin
        tmp_V_fu_202 <= fifo_config_in_V_V_dout;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state65) & (1'b0 == ap_block_state65_on_subcall_done))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state58) & (tmp_306_i_i_reg_1537 == 1'd1) & (tmp_327_i_i_reg_1728 == 1'd0) & (tmp_323_i_i_reg_1718 == 1'd0) & (tmp_320_i_i_reg_1676 == 1'd0) & (brmerge_i_i_reg_1640 == 1'd0))) begin
        ap_phi_mux_done_i_i_be_phi_fu_335_p24 = tmp_330_i_i_reg_1738;
    end else begin
        ap_phi_mux_done_i_i_be_phi_fu_335_p24 = done_i_i_be_reg_330;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state58) & (tmp_306_i_i_reg_1537 == 1'd1) & (tmp_327_i_i_reg_1728 == 1'd0) & (tmp_323_i_i_reg_1718 == 1'd0) & (tmp_320_i_i_reg_1676 == 1'd0) & (brmerge_i_i_reg_1640 == 1'd0))) begin
        ap_phi_mux_layer_start_i_i_be_phi_fu_291_p24 = 1'd1;
    end else begin
        ap_phi_mux_layer_start_i_i_be_phi_fu_291_p24 = layer_start_i_i_be_reg_286;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state65) & (1'b0 == ap_block_state65_on_subcall_done))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op238_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((ap_predicate_op231_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        cout_burst_buf_ping_s_address0 = grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_address0;
    end else if ((((1'b1 == ap_CS_fsm_state65) & (tmp_reg_1473 == 1'd1) & (p_0961_i_i_reg_238 == 1'd0)) | ((ap_predicate_op235_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        cout_burst_buf_ping_s_address0 = grp_cout_write_ddr_write_fu_371_cout_burst_buf_V_address0;
    end else begin
        cout_burst_buf_ping_s_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_op238_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((ap_predicate_op231_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        cout_burst_buf_ping_s_ce0 = grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_ce0;
    end else if ((((1'b1 == ap_CS_fsm_state65) & (tmp_reg_1473 == 1'd1) & (p_0961_i_i_reg_238 == 1'd0)) | ((ap_predicate_op235_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        cout_burst_buf_ping_s_ce0 = grp_cout_write_ddr_write_fu_371_cout_burst_buf_V_ce0;
    end else begin
        cout_burst_buf_ping_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op238_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((ap_predicate_op231_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        cout_burst_buf_ping_s_ce1 = grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_ce1;
    end else begin
        cout_burst_buf_ping_s_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op238_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((ap_predicate_op231_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        cout_burst_buf_ping_s_we0 = grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_we0;
    end else begin
        cout_burst_buf_ping_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op238_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((ap_predicate_op231_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        cout_burst_buf_ping_s_we1 = grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_we1;
    end else begin
        cout_burst_buf_ping_s_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op234_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        cout_burst_buf_pong_s_address0 = grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_address0;
    end else if ((((1'b1 == ap_CS_fsm_state65) & (p_0961_i_i_reg_238 == 1'd0) & (tmp_reg_1473 == 1'd0)) | ((ap_predicate_op232_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        cout_burst_buf_pong_s_address0 = grp_cout_write_ddr_write_fu_371_cout_burst_buf_V_address0;
    end else begin
        cout_burst_buf_pong_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_predicate_op234_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        cout_burst_buf_pong_s_ce0 = grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_ce0;
    end else if ((((1'b1 == ap_CS_fsm_state65) & (p_0961_i_i_reg_238 == 1'd0) & (tmp_reg_1473 == 1'd0)) | ((ap_predicate_op232_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        cout_burst_buf_pong_s_ce0 = grp_cout_write_ddr_write_fu_371_cout_burst_buf_V_ce0;
    end else begin
        cout_burst_buf_pong_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op234_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        cout_burst_buf_pong_s_ce1 = grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_ce1;
    end else begin
        cout_burst_buf_pong_s_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op234_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        cout_burst_buf_pong_s_we0 = grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_we0;
    end else begin
        cout_burst_buf_pong_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op234_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        cout_burst_buf_pong_s_we1 = grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_we1;
    end else begin
        cout_burst_buf_pong_s_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state10) & (layer_start_i_i_reg_250 == 1'd1)) | ((1'b1 == ap_CS_fsm_state6) & (layer_start_i_i_reg_250 == 1'd1) & (done_i_i_reg_262 == 1'd0)))) begin
        fifo_config_in_V_V_blk_n = fifo_config_in_V_V_empty_n;
    end else begin
        fifo_config_in_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | (~((fifo_config_in_V_V_empty_n == 1'b0) & (layer_start_i_i_reg_250 == 1'd1)) & (1'b1 == ap_CS_fsm_state10) & (layer_start_i_i_reg_250 == 1'd1)) | ((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state9)) | ((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | (~((ap_predicate_op139_read_state6 == 1'b1) & (fifo_config_in_V_V_empty_n == 1'b0)) & (ap_predicate_op139_read_state6 == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | ((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        fifo_config_in_V_V_read = 1'b1;
    end else begin
        fifo_config_in_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op238_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((ap_predicate_op234_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((ap_predicate_op231_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        fifo_cout_V_V_read = grp_cout_write_fifo_read_fu_394_fifo_cout_V_V_read;
    end else begin
        fifo_cout_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        global_cout_V_offset_blk_n = global_cout_V_offset_empty_n;
    end else begin
        global_cout_V_offset_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        global_cout_V_offset_read = 1'b1;
    end else begin
        global_cout_V_offset_read = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op235_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((ap_predicate_op232_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        grp_cout_write_ddr_write_fu_371_change_layout = change_layout_prev_l_reg_1625;
    end else if ((((1'b1 == ap_CS_fsm_state65) & (tmp_reg_1473 == 1'd1) & (p_0961_i_i_reg_238 == 1'd0)) | ((1'b1 == ap_CS_fsm_state65) & (p_0961_i_i_reg_238 == 1'd0) & (tmp_reg_1473 == 1'd0)))) begin
        grp_cout_write_ddr_write_fu_371_change_layout = change_layout_prev_l_1_reg_1477;
    end else begin
        grp_cout_write_ddr_write_fu_371_change_layout = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state65) & (tmp_reg_1473 == 1'd1) & (p_0961_i_i_reg_238 == 1'd0)) | ((ap_predicate_op235_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        grp_cout_write_ddr_write_fu_371_cout_burst_buf_V_q0 = cout_burst_buf_ping_s_q0;
    end else if ((((1'b1 == ap_CS_fsm_state65) & (p_0961_i_i_reg_238 == 1'd0) & (tmp_reg_1473 == 1'd0)) | ((ap_predicate_op232_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        grp_cout_write_ddr_write_fu_371_cout_burst_buf_V_q0 = cout_burst_buf_pong_s_q0;
    end else begin
        grp_cout_write_ddr_write_fu_371_cout_burst_buf_V_q0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_op235_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((ap_predicate_op232_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        grp_cout_write_ddr_write_fu_371_en = en_prev_load_1_reg_1635;
    end else if ((((1'b1 == ap_CS_fsm_state65) & (tmp_reg_1473 == 1'd1) & (p_0961_i_i_reg_238 == 1'd0)) | ((1'b1 == ap_CS_fsm_state65) & (p_0961_i_i_reg_238 == 1'd0) & (tmp_reg_1473 == 1'd0)))) begin
        grp_cout_write_ddr_write_fu_371_en = en_prev_load_reg_1487;
    end else begin
        grp_cout_write_ddr_write_fu_371_en = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_op235_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((ap_predicate_op232_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        grp_cout_write_ddr_write_fu_371_up_sample = up_sample_prev_load_1_reg_1630;
    end else if ((((1'b1 == ap_CS_fsm_state65) & (tmp_reg_1473 == 1'd1) & (p_0961_i_i_reg_238 == 1'd0)) | ((1'b1 == ap_CS_fsm_state65) & (p_0961_i_i_reg_238 == 1'd0) & (tmp_reg_1473 == 1'd0)))) begin
        grp_cout_write_ddr_write_fu_371_up_sample = up_sample_prev_load_reg_1482;
    end else begin
        grp_cout_write_ddr_write_fu_371_up_sample = 'bx;
    end
end

always @ (*) begin
    if (((ap_predicate_op234_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_q0 = cout_burst_buf_pong_s_q0;
    end else if ((((ap_predicate_op238_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((ap_predicate_op231_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_q0 = cout_burst_buf_ping_s_q0;
    end else begin
        grp_cout_write_fifo_read_fu_394_cout_burst_buf_V_q0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (tmp_306_i_i_reg_1537 == 1'd1) & (brmerge_i_i_reg_1640 == 1'd0))) begin
        grp_fu_1093_ap_start = 1'b1;
    end else begin
        grp_fu_1093_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state65) & (tmp_reg_1473 == 1'd1) & (p_0961_i_i_reg_238 == 1'd0)) | ((1'b1 == ap_CS_fsm_state65) & (p_0961_i_i_reg_238 == 1'd0) & (tmp_reg_1473 == 1'd0)) | ((ap_predicate_op235_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((ap_predicate_op232_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((1'b1 == ap_CS_fsm_state11) & (tmp_reg_1473 == 1'd1) & (tmp_311_i_i_fu_997_p2 == 1'd1) & (tmp_312_i_i_fu_1003_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state11) & (tmp_311_i_i_fu_997_p2 == 1'd1) & (tmp_reg_1473 == 1'd0) & (tmp_312_i_i_fu_1003_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state6) & (tmp_fu_740_p1 == 1'd1) & (ap_phi_mux_done_i_i_phi_fu_266_p4 == 1'd1) & (ap_phi_mux_p_0961_i_i_phi_fu_242_p4 == 1'd0)) | ((1'b1 == ap_CS_fsm_state6) & (ap_phi_mux_done_i_i_phi_fu_266_p4 == 1'd1) & (tmp_fu_740_p1 == 1'd0) & (ap_phi_mux_p_0961_i_i_phi_fu_242_p4 == 1'd0)))) begin
        m_axi_global_cout_V_AWVALID = grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWVALID;
    end else begin
        m_axi_global_cout_V_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state65) & (tmp_reg_1473 == 1'd1) & (p_0961_i_i_reg_238 == 1'd0)) | ((1'b1 == ap_CS_fsm_state65) & (p_0961_i_i_reg_238 == 1'd0) & (tmp_reg_1473 == 1'd0)) | ((ap_predicate_op235_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((ap_predicate_op232_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((1'b1 == ap_CS_fsm_state11) & (tmp_reg_1473 == 1'd1) & (tmp_311_i_i_fu_997_p2 == 1'd1) & (tmp_312_i_i_fu_1003_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state11) & (tmp_311_i_i_fu_997_p2 == 1'd1) & (tmp_reg_1473 == 1'd0) & (tmp_312_i_i_fu_1003_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state6) & (tmp_fu_740_p1 == 1'd1) & (ap_phi_mux_done_i_i_phi_fu_266_p4 == 1'd1) & (ap_phi_mux_p_0961_i_i_phi_fu_242_p4 == 1'd0)) | ((1'b1 == ap_CS_fsm_state6) & (ap_phi_mux_done_i_i_phi_fu_266_p4 == 1'd1) & (tmp_fu_740_p1 == 1'd0) & (ap_phi_mux_p_0961_i_i_phi_fu_242_p4 == 1'd0)))) begin
        m_axi_global_cout_V_BREADY = grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_BREADY;
    end else begin
        m_axi_global_cout_V_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state65) & (tmp_reg_1473 == 1'd1) & (p_0961_i_i_reg_238 == 1'd0)) | ((1'b1 == ap_CS_fsm_state65) & (p_0961_i_i_reg_238 == 1'd0) & (tmp_reg_1473 == 1'd0)) | ((ap_predicate_op235_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((ap_predicate_op232_call_state12 == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((1'b1 == ap_CS_fsm_state11) & (tmp_reg_1473 == 1'd1) & (tmp_311_i_i_fu_997_p2 == 1'd1) & (tmp_312_i_i_fu_1003_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state11) & (tmp_311_i_i_fu_997_p2 == 1'd1) & (tmp_reg_1473 == 1'd0) & (tmp_312_i_i_fu_1003_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state6) & (tmp_fu_740_p1 == 1'd1) & (ap_phi_mux_done_i_i_phi_fu_266_p4 == 1'd1) & (ap_phi_mux_p_0961_i_i_phi_fu_242_p4 == 1'd0)) | ((1'b1 == ap_CS_fsm_state6) & (ap_phi_mux_done_i_i_phi_fu_266_p4 == 1'd1) & (tmp_fu_740_p1 == 1'd0) & (ap_phi_mux_p_0961_i_i_phi_fu_242_p4 == 1'd0)))) begin
        m_axi_global_cout_V_WVALID = grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_WVALID;
    end else begin
        m_axi_global_cout_V_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if ((~((ap_predicate_op139_read_state6 == 1'b1) & (fifo_config_in_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6) & (ap_phi_mux_done_i_i_phi_fu_266_p4 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state65;
            end else if ((~((ap_predicate_op139_read_state6 == 1'b1) & (fifo_config_in_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6) & (ap_phi_mux_layer_start_i_i_phi_fu_254_p4 == 1'd0) & (done_i_i_reg_262 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if ((~((ap_predicate_op139_read_state6 == 1'b1) & (fifo_config_in_V_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6) & (layer_start_i_i_reg_250 == 1'd1) & (done_i_i_reg_262 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((fifo_config_in_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if ((~((fifo_config_in_V_V_empty_n == 1'b0) & (layer_start_i_i_reg_250 == 1'd1)) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (tmp_306_i_i_reg_1537 == 1'd1) & (brmerge_i_i_reg_1640 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else if (((1'b1 == ap_CS_fsm_state13) & (tmp_306_i_i_reg_1537 == 1'd0) & (brmerge_i_i_reg_1640 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state60;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((1'b1 == ap_CS_fsm_state14) & (grp_fu_642_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (grp_fu_652_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((1'b1 == ap_CS_fsm_state16) & (tmp_329_i_i_fu_1133_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            if (((1'b1 == ap_CS_fsm_state54) & (tmp_320_i_i_reg_1676 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state59;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state55;
            end
        end
        ap_ST_fsm_state55 : begin
            if (((1'b1 == ap_CS_fsm_state55) & (grp_fu_652_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end
        end
        ap_ST_fsm_state56 : begin
            if (((1'b1 == ap_CS_fsm_state56) & (tmp_327_i_i_fu_1231_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state57;
            end
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state60 : begin
            if (((1'b1 == ap_CS_fsm_state60) & (tmp_314_i_i_fu_1254_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state61;
            end
        end
        ap_ST_fsm_state61 : begin
            if (((1'b1 == ap_CS_fsm_state61) & (grp_fu_642_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state62;
            end
        end
        ap_ST_fsm_state62 : begin
            if (((1'b1 == ap_CS_fsm_state62) & (grp_fu_652_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state63;
            end
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state65 : begin
            if (((1'b1 == ap_CS_fsm_state65) & (1'b0 == ap_block_state65_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state65;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LAYER_IN_NUM_V_fu_888_p1 = tmp_V_67_fu_206[31:0];

assign LAYER_OUT_H_HW_V_fu_868_p4 = {{tmp_V_fu_202[159:128]}};

assign LAYER_OUT_H_V_fu_922_p4 = {{tmp_V_67_fu_206[159:128]}};

assign LAYER_OUT_NUM_T_prev_1_fu_1015_p1 = LAYER_OUT_NUM_T_V_reg_1507;

assign LAYER_OUT_W_HW_V_fu_878_p4 = {{tmp_V_fu_202[191:160]}};

assign LAYER_OUT_W_V_fu_933_p4 = {{tmp_V_67_fu_206[191:160]}};

assign STRIDE_V_fu_760_p4 = {{tmp_V_68_fu_210[191:160]}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state54 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd58];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state60 = ap_CS_fsm[32'd59];

assign ap_CS_fsm_state61 = ap_CS_fsm[32'd60];

assign ap_CS_fsm_state62 = ap_CS_fsm[32'd61];

assign ap_CS_fsm_state63 = ap_CS_fsm[32'd62];

assign ap_CS_fsm_state64 = ap_CS_fsm[32'd63];

assign ap_CS_fsm_state65 = ap_CS_fsm[32'd64];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (fifo_config_in_V_V_empty_n == 1'b0) | (ap_start == 1'b0) | (global_cout_V_offset_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state10 = ((fifo_config_in_V_V_empty_n == 1'b0) & (layer_start_i_i_reg_250 == 1'd1));
end

always @ (*) begin
    ap_block_state12_on_subcall_done = (((ap_predicate_op235_call_state12 == 1'b1) & (grp_cout_write_ddr_write_fu_371_ap_done == 1'b0)) | ((ap_predicate_op232_call_state12 == 1'b1) & (grp_cout_write_ddr_write_fu_371_ap_done == 1'b0)) | ((ap_predicate_op238_call_state12 == 1'b1) & (grp_cout_write_fifo_read_fu_394_ap_done == 1'b0)) | ((ap_predicate_op234_call_state12 == 1'b1) & (grp_cout_write_fifo_read_fu_394_ap_done == 1'b0)) | ((ap_predicate_op231_call_state12 == 1'b1) & (grp_cout_write_fifo_read_fu_394_ap_done == 1'b0)));
end

always @ (*) begin
    ap_block_state6 = ((ap_predicate_op139_read_state6 == 1'b1) & (fifo_config_in_V_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state65_on_subcall_done = (((ap_predicate_op438_call_state65 == 1'b1) & (grp_cout_write_ddr_write_fu_371_ap_done == 1'b0)) | ((ap_predicate_op436_call_state65 == 1'b1) & (grp_cout_write_ddr_write_fu_371_ap_done == 1'b0)));
end

always @ (*) begin
    ap_block_state6_ignore_call0 = ((ap_predicate_op139_read_state6 == 1'b1) & (fifo_config_in_V_V_empty_n == 1'b0));
end

assign ap_phi_mux_done_i_i_phi_fu_266_p4 = done_i_i_reg_262;

assign ap_phi_mux_layer_start_i_i_phi_fu_254_p4 = layer_start_i_i_reg_250;

assign ap_phi_mux_p_0961_i_i_phi_fu_242_p4 = p_0961_i_i_reg_238;

always @ (*) begin
    ap_predicate_op139_read_state6 = ((layer_start_i_i_reg_250 == 1'd1) & (done_i_i_reg_262 == 1'd0));
end

always @ (*) begin
    ap_predicate_op231_call_state12 = ((tmp_311_i_i_reg_1612 == 1'd1) & (tmp_312_i_i_reg_1616 == 1'd0) & (tmp_reg_1473 == 1'd0));
end

always @ (*) begin
    ap_predicate_op232_call_state12 = ((tmp_311_i_i_reg_1612 == 1'd1) & (tmp_312_i_i_reg_1616 == 1'd0) & (tmp_reg_1473 == 1'd0));
end

always @ (*) begin
    ap_predicate_op234_call_state12 = ((tmp_311_i_i_reg_1612 == 1'd1) & (tmp_reg_1473 == 1'd1) & (tmp_312_i_i_reg_1616 == 1'd0));
end

always @ (*) begin
    ap_predicate_op235_call_state12 = ((tmp_311_i_i_reg_1612 == 1'd1) & (tmp_reg_1473 == 1'd1) & (tmp_312_i_i_reg_1616 == 1'd0));
end

always @ (*) begin
    ap_predicate_op238_call_state12 = ((tmp_312_i_i_reg_1616 == 1'd1) & (tmp_311_i_i_reg_1612 == 1'd1));
end

always @ (*) begin
    ap_predicate_op436_call_state65 = ((p_0961_i_i_reg_238 == 1'd0) & (tmp_reg_1473 == 1'd0));
end

always @ (*) begin
    ap_predicate_op438_call_state65 = ((tmp_reg_1473 == 1'd1) & (p_0961_i_i_reg_238 == 1'd0));
end

assign brmerge_i_i_fu_1089_p2 = (up_sample_reg_1552 | max_pool_reg_1547);

assign change_layout_fu_991_p2 = (p_i_i_fu_985_p2 & or_cond_i_i_fu_968_p2);

assign en_fu_832_p2 = (tmp_541_fu_824_p3 | tmp_306_i_i_fu_818_p2);

assign grp_cout_write_ddr_write_fu_371_ap_start = grp_cout_write_ddr_write_fu_371_ap_start_reg;

assign grp_cout_write_fifo_read_fu_394_ap_start = grp_cout_write_fifo_read_fu_394_ap_start_reg;

assign grp_cout_write_fifo_read_fu_394_en = en_reg_1541;

assign grp_cout_write_fifo_read_fu_394_up_sample = up_sample_reg_1552;

assign grp_fu_525_p2 = (LAYER_IN_H_T_V_reg_1515 + in_h_iter_prev_fu_190);

assign grp_fu_530_p2 = (LAYER_IN_W_T_V_reg_1524 + in_w_iter_prev_fu_122);

assign grp_fu_542_p2 = (layer_iter_i_i_fu_110 + 32'd1);

assign grp_fu_642_p2 = ((reg_630 < LAYER_IN_H_V_reg_1581) ? 1'b1 : 1'b0);

assign grp_fu_652_p2 = ((reg_634 < LAYER_IN_W_V_reg_1587) ? 1'b1 : 1'b0);

assign grp_fu_662_p2 = ((reg_638 == LAYER_BATCH_V_reg_1461) ? 1'b1 : 1'b0);

assign ind_w_2_i_i_fu_1207_p3 = ((tmp_316_i_i_fu_1171_p2[0:0] === 1'b1) ? p_ind_w_i_i_fu_1185_p3 : ind_w_prev_fu_118);

assign ind_w_fu_1180_p2 = (num_tile_2_reg_1685 + ind_w_prev_fu_118);

assign ind_w_t_3_i_i_fu_1215_p3 = ((tmp_316_i_i_fu_1171_p2[0:0] === 1'b1) ? p_i_i_62_fu_1193_p3 : ind_w_t_prev_fu_114);

assign m_axi_global_cout_V_ARADDR = 64'd0;

assign m_axi_global_cout_V_ARBURST = 2'd0;

assign m_axi_global_cout_V_ARCACHE = 4'd0;

assign m_axi_global_cout_V_ARID = 1'd0;

assign m_axi_global_cout_V_ARLEN = 32'd0;

assign m_axi_global_cout_V_ARLOCK = 2'd0;

assign m_axi_global_cout_V_ARPROT = 3'd0;

assign m_axi_global_cout_V_ARQOS = 4'd0;

assign m_axi_global_cout_V_ARREGION = 4'd0;

assign m_axi_global_cout_V_ARSIZE = 3'd0;

assign m_axi_global_cout_V_ARUSER = 1'd0;

assign m_axi_global_cout_V_ARVALID = 1'b0;

assign m_axi_global_cout_V_AWADDR = grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWADDR;

assign m_axi_global_cout_V_AWBURST = grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWBURST;

assign m_axi_global_cout_V_AWCACHE = grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWCACHE;

assign m_axi_global_cout_V_AWID = grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWID;

assign m_axi_global_cout_V_AWLEN = grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWLEN;

assign m_axi_global_cout_V_AWLOCK = grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWLOCK;

assign m_axi_global_cout_V_AWPROT = grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWPROT;

assign m_axi_global_cout_V_AWQOS = grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWQOS;

assign m_axi_global_cout_V_AWREGION = grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWREGION;

assign m_axi_global_cout_V_AWSIZE = grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWSIZE;

assign m_axi_global_cout_V_AWUSER = grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_AWUSER;

assign m_axi_global_cout_V_RREADY = 1'b0;

assign m_axi_global_cout_V_WDATA = grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_WDATA;

assign m_axi_global_cout_V_WID = grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_WID;

assign m_axi_global_cout_V_WLAST = grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_WLAST;

assign m_axi_global_cout_V_WSTRB = grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_WSTRB;

assign m_axi_global_cout_V_WUSER = grp_cout_write_ddr_write_fu_371_m_axi_global_cout_V_WUSER;

assign max_pool_fu_848_p2 = ((tmp_542_fu_838_p4 == 2'd0) ? 1'b1 : 1'b0);

assign num_iter_1_fu_1225_p2 = (tmp_326_i_i_fu_1222_p1 + num_iter_prev_fu_126);

assign num_iter_2_fu_1127_p2 = (tmp_328_i_i_fu_1124_p1 + num_iter_prev_fu_126);

assign num_iter_fu_1118_p2 = (tmp_313_i_i_fu_1115_p1 + num_iter_prev_fu_126);

assign num_tile_1_i_i_fu_1200_p3 = ((tmp_316_i_i_fu_1171_p2[0:0] === 1'b1) ? 32'd0 : num_tile_2_reg_1685);

assign num_tile_2_fu_1153_p2 = (num_tile_prev_2_reg_1467 + 32'd1);

assign or_cond_i_i_fu_968_p2 = (tmp_308_i_i_fu_963_p2 | tmp_307_i_i_fu_957_p2);

assign p_1713_v_cast_cast_ca_fu_1158_p3 = ((tmp_318_i_i_reg_1644[0:0] === 1'b1) ? 32'd2 : 32'd1);

assign p_4_i_i_61_fu_1165_p2 = (p_1713_v_cast_cast_ca_fu_1158_p3 + ind_w_t_prev_fu_114);

assign p_4_i_i_fu_1262_p3 = ((tmp_325_i_i_reg_1753[0:0] === 1'b1) ? 32'd0 : reg_638);

assign p_5_i_i_fu_1141_p3 = ((tmp_331_i_i_reg_1670[0:0] === 1'b1) ? 32'd0 : reg_638);

assign p_6_i_i_fu_1243_p3 = ((tmp_330_i_i_reg_1738[0:0] === 1'b1) ? 32'd0 : layer_iter_4_reg_1732);

assign p_Result_s_fu_951_p2 = ((tmp_i_i_fu_944_p3 != 10'd0) ? 1'b1 : 1'b0);

assign p_i_i_62_fu_1193_p3 = ((tmp_319_i_i_fu_1175_p2[0:0] === 1'b1) ? 32'd0 : p_4_i_i_61_reg_1697);

assign p_i_i_fu_985_p2 = (tmp_310_i_i_fu_980_p2 | tmp_309_i_i_fu_974_p2);

assign p_ind_w_i_i_fu_1185_p3 = ((tmp_319_i_i_fu_1175_p2[0:0] === 1'b1) ? ind_w_fu_1180_p2 : ind_w_prev_fu_118);

assign task_cnt_fu_1009_p2 = (reg_560 + 32'd1);

assign tmp_306_i_i_fu_818_p2 = ((STRIDE_V_fu_760_p4 == 32'd2) ? 1'b1 : 1'b0);

assign tmp_307_i_i_fu_957_p2 = ((LAYER_OUT_W_HW_V_fu_878_p4 == LAYER_OUT_W_V_fu_933_p4) ? 1'b1 : 1'b0);

assign tmp_308_i_i_fu_963_p2 = ((LAYER_OUT_W_HW_V_fu_878_p4 == LAYER_IN_W_T_V_reg_1524) ? 1'b1 : 1'b0);

assign tmp_309_i_i_fu_974_p2 = ((LAYER_OUT_H_HW_V_fu_868_p4 == LAYER_OUT_H_V_fu_922_p4) ? 1'b1 : 1'b0);

assign tmp_310_i_i_fu_980_p2 = ((LAYER_OUT_H_HW_V_fu_868_p4 == LAYER_IN_H_T_V_reg_1515) ? 1'b1 : 1'b0);

assign tmp_311_i_i_fu_997_p2 = ((tmp_i_i_fu_944_p3 == 10'd0) ? 1'b1 : 1'b0);

assign tmp_312_i_i_fu_1003_p2 = ((reg_560 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_313_i_i_fu_1115_p1 = LAYER_IN_NUM_T_V_reg_1502;

assign tmp_314_i_i_fu_1254_p2 = ((num_iter_reg_1649 < LAYER_IN_NUM_V_reg_1570) ? 1'b1 : 1'b0);

assign tmp_316_i_i_fu_1171_p2 = ((num_tile_2_reg_1685 == ret_V_reg_1692) ? 1'b1 : 1'b0);

assign tmp_317_i_i_fu_1097_p4 = {{p_Val2_17_reg_1492[159:129]}};

assign tmp_318_i_i_fu_1110_p2 = ((tmp_354_i_i_fu_1106_p1 == LAYER_OUT_W_HW_V_reg_1564) ? 1'b1 : 1'b0);

assign tmp_319_i_i_fu_1175_p2 = ((p_4_i_i_61_reg_1697 == 32'd2) ? 1'b1 : 1'b0);

assign tmp_326_i_i_fu_1222_p1 = LAYER_OUT_NUM_T_V_reg_1507;

assign tmp_327_i_i_fu_1231_p2 = ((num_iter_1_reg_1722 < LAYER_OUT_NUM_V_reg_1575) ? 1'b1 : 1'b0);

assign tmp_328_i_i_fu_1124_p1 = LAYER_OUT_NUM_T_V_reg_1507;

assign tmp_329_i_i_fu_1133_p2 = ((num_iter_2_reg_1661 < LAYER_OUT_NUM_V_reg_1575) ? 1'b1 : 1'b0);

assign tmp_330_i_i_fu_1239_p2 = ((layer_iter_4_reg_1732 == LAYER_BATCH_V_reg_1461) ? 1'b1 : 1'b0);

assign tmp_354_i_i_fu_1106_p1 = tmp_317_i_i_fu_1097_p4;

assign tmp_541_fu_824_p3 = tmp_V_69_fu_214[32'd5];

assign tmp_542_fu_838_p4 = {{tmp_V_69_fu_214[2:1]}};

assign tmp_fu_740_p1 = num_tile_fu_150[0:0];

assign tmp_i_i_fu_944_p3 = {{tmp_540_reg_1532}, {9'd0}};

always @ (posedge ap_clk) begin
    reg_605[31:16] <= 16'b0000000000000000;
    LAYER_OUT_NUM_T_prev_fu_174[31:16] <= 16'b0000000000000000;
end

endmodule //cout_write
